const yemekSorulari = [
    { soru: "Pizza hangi ülkenin yemeğidir?", A: "İtalya", B: "Fransa", C: "Yunanistan", D: "İspanya", E: "Türkiye", dogru: "A", aciklama: "Modern pizza Napoli, İtalya'da doğmuştur." },
    { soru: "Suşi hangi ülkenin yemeğidir?", A: "Japonya", B: "Çin", C: "Kore", D: "Tayland", E: "Vietnam", dogru: "A", aciklama: "Suşi, Japon mutfağının ikonik yemeğidir." },
    { soru: "Lahmacun hangi mutfağa aittir?", A: "Türk", B: "Yunan", C: "Arap", D: "İtalyan", E: "Ermeni", dogru: "A", aciklama: "Lahmacun, ince hamur üzerine kıymalı harçla yapılan Türk yemeğidir." },
    { soru: "Hangisi bir tatlı değildir?", A: "Mantı", B: "Baklava", C: "Sütlaç", D: "Kazandibi", E: "Aşure", dogru: "A", aciklama: "Mantı, yoğurtlu ve salçalı sosla servis edilen bir ana yemektir." },
    { soru: "Humusun ana malzemesi nedir?", A: "Nohut", B: "Fasulye", C: "Mercimek", D: "Bezelye", E: "Barbunya", dogru: "A", aciklama: "Humus, nohut ezmesi, tahin, limon ve sarımsakla yapılır." },
    { soru: "Kruvasan hangi ülkenin hamur işidir?", A: "Fransa", B: "İtalya", C: "İspanya", D: "Yunanistan", E: "Türkiye", dogru: "A", aciklama: "Kruvasan, Fransız mutfağının ünlü tereyağlı hamur işidir." },
    { soru: "Matcha nedir?", A: "Yeşil çay tozu", B: "Kahve türü", C: "Sıcak çikolata", D: "Salep", E: "Boza", dogru: "A", aciklama: "Matcha, öğütülmüş yeşil çay yapraklarından elde edilir." },
    { soru: "Çedar peyniri hangi ülkeye aittir?", A: "İngiltere", B: "İtalya", C: "Fransa", D: "Hollanda", E: "İsviçre", dogru: "A", aciklama: "Çedar, İngiliz kökenli sert bir peynirdir." },
    { soru: "Hangisi bir çorba değildir?", A: "İmambayıldı", B: "Mercimek", C: "Tarhana", D: "Ezogelin", E: "Domates", dogru: "A", aciklama: "İmambayıldı, zeytinyağlı bir patlıcan yemeğidir." },
    { soru: "Türk kahvesi nasıl servis edilir?", A: "Sade, az şekerli, orta, şekerli", B: "Sadece sade", C: "Sütlü", D: "Kremalı", E: "Soğuk", dogru: "A", aciklama: "Türk kahvesi dört farklı şekilde servis edilir." },
    { soru: "Dönerin ana malzemesi nedir?", A: "Et (Tavuk, Kuzu, Dana)", B: "Sadece tavuk", C: "Sadece kuzu", D: "Sadece dana", E: "Balık", dogru: "A", aciklama: "Döner; tavuk, kuzu veya dana etinden yapılabilir." },
    { soru: "Hangisi bir makarna çeşidi değildir?", A: "Risotto", B: "Spagetti", C: "Fettuccine", D: "Penne", E: "Lazanya", dogru: "A", aciklama: "Risotto, pirinçten yapılan bir İtalyan yemeğidir." },
    { soru: "Baklava hangi özel günlerde sıkça tüketilir?", A: "Bayramlar", B: "Düğünler", C: "Cenazeler", D: "Doğum günleri", E: "Hepsi", dogru: "A", aciklama: "Baklava, özellikle Ramazan ve Kurban bayramlarında ikram edilir." },
    { soru: "Hangisi bir kebap çeşidi değildir?", A: "Kayseri Kebabı", B: "Adana Kebabı", C: "Urfa Kebabı", D: "İskender Kebabı", E: "Beyti Kebabı", dogru: "A", aciklama: "Kayseri mantısıyla ünlüdür, Kayseri kebabı yoktur." },
    { soru: "Guacamole hangi meyveden yapılır?", A: "Avokado", B: "Muz", C: "Mango", D: "Ananas", E: "Domates", dogru: "A", aciklama: "Guacamole, avokado ezmesi bazlı bir Meksika sosudur." },
    { soru: "Hangisi bir İtalyan peyniri değildir?", A: "Çedar", B: "Mozzarella", C: "Parmesan", D: "Gorgonzola", E: "Ricotta", dogru: "A", aciklama: "Çedar, İngiliz peyniridir." },
    { soru: "Paella hangi ülkenin yemeğidir?", A: "İspanya", B: "İtalya", C: "Portekiz", D: "Meksika", E: "Yunanistan", dogru: "A", aciklama: "Paella, İspanya'nın Valensiya bölgesine özgü pirinç yemeğidir." },
    { soru: "Hangisi bir çiğ köfte malzemesi değildir?", A: "Peynir", B: "İnce Bulgur", C: "Salça", D: "Soğan", E: "Baharat", dogru: "A", aciklama: "Çiğ köftede peynir kullanılmaz." },
    { soru: "Hangisi bir Türk tatlısı değildir?", A: "Tiramisu", B: "Baklava", C: "Künefe", D: "Sütlaç", E: "Aşure", dogru: "A", aciklama: "Tiramisu, İtalyan tatlısıdır." },
    { soru: "Hangisi bir fast-food zinciri değildir?", A: "Starbucks (Kahve zinciri)", B: "McDonald's", C: "Burger King", D: "KFC", E: "Subway", dogru: "A", aciklama: "Starbucks öncelikle kahve zinciridir." },
    { soru: "Kırmızı et yemeyen kişilere ne denir?", A: "Vejetaryen", B: "Vegan", C: "Pesketaryen", D: "Frutaryen", E: "Ortoreksik", dogru: "A", aciklama: "Vejetaryenler et yemez, veganlar hiçbir hayvansal ürün tüketmez." },
    { soru: "Zeytinyağlı yemeklerin ana malzemesi nedir?", A: "Zeytinyağı", B: "Tereyağı", C: "Ayçiçek yağı", D: "Margarin", E: "Kuyruk yağı", dogru: "A", aciklama: "Zeytinyağlılar, adından da anlaşılacağı gibi zeytinyağı ile yapılır." },
    { soru: "Hangisi bir baharat değildir?", A: "Şeker", B: "Karabiber", C: "Kimyon", D: "Kekik", E: "Pul Biber", dogru: "A", aciklama: "Şeker, tatlandırıcıdır; baharat değildir." },
    { soru: "Hangisi bir baklagil değildir?", A: "Patates", B: "Nohut", C: "Mercimek", D: "Fasulye", E: "Bezelye", dogru: "A", aciklama: "Patates, kök sebzedir; baklagil değildir." },
    { soru: "Hangisi bir narenciye değildir?", A: "Elma", B: "Portakal", C: "Limon", D: "Mandalina", E: "Greyfurt", dogru: "A", aciklama: "Elma, narenciye ailesinden değildir." },
    { soru: "Hangisi bir kuruyemiş değildir?", A: "Leblebi", B: "Ceviz", C: "Badem", D: "Fındık", E: "Antep Fıstığı", dogru: "A", aciklama: "Leblebi, nohuttan yapılır; kuruyemiş olarak tüketilse de teknik olarak baklagildir." },
    { soru: "Hangisi bir içecek değildir?", A: "Puding", B: "Ayran", C: "Kola", D: "Çay", E: "Kahve", dogru: "A", aciklama: "Puding, bir tatlıdır." },
    { soru: "Hangisi bir süt ürünü değildir?", A: "Yumurta", B: "Yoğurt", C: "Peynir", D: "Tereyağı", E: "Kaymak", dogru: "A", aciklama: "Yumurta, hayvansal protein kaynağıdır ancak süt ürünü değildir." },
    { soru: "Hangisi bir ekmek türü değildir?", A: "Kek", B: "Somun", C: "Baget", D: "Lavaş", E: "Pide", dogru: "A", aciklama: "Kek, bir tatlı veya pastane ürünüdür." },
    { soru: "Hangisi bir pilav türü değildir?", A: "Makarna", B: "Pirinç Pilavı", C: "Bulgur Pilavı", D: "İç Pilav", E: "Özbek Pilavı", dogru: "A", aciklama: "Makarna, pilav değil, ayrı bir yemek kategorisidir." },
    { soru: "Hangisi bir zeytinyağlı yemek değildir?", A: "Karnıyarık", B: "İmambayıldı", C: "Zeytinyağlı Fasulye", D: "Zeytinyağlı Enginar", E: "Zeytinyağlı Yaprak Sarma", dogru: "A", aciklama: "Karnıyarık, kızartılarak yapılan etli bir yemektir." },
    { soru: "Hangisi bir hamur işi değildir?", A: "Pilav", B: "Börek", C: "Poğaça", D: "Simit", E: "Açma", dogru: "A", aciklama: "Pilav, pirinç veya bulgurdan yapılır." },
    { soru: "Hangisi bir salata türü değildir?", A: "Mücver", B: "Çoban Salata", C: "Sezar Salata", D: "Mevsim Salata", E: "Gavurdağı Salatası", dogru: "A", aciklama: "Mücver, kabakla yapılan bir kızartma yemeğidir." },
    { soru: "Hangisi bir deniz ürünü değildir?", A: "Kuzu", B: "Balık", C: "Karides", D: "Kalamar", E: "Midye", dogru: "A", aciklama: "Kuzu, kara hayvanıdır." },
    { soru: "Hangisi bir meyve değildir?", A: "Patates", B: "Elma", C: "Armut", D: "Muz", E: "Çilek", dogru: "A", aciklama: "Patates, sebzedir (kök)." },
    { soru: "Hangisi bir sebze değildir?", A: "Çilek", B: "Domates", C: "Biber", D: "Patlıcan", E: "Salatalık", dogru: "A", aciklama: "Çilek, meyvedir." },
    { soru: "Hangisi bir Türk yemeği değildir?", A: "Suşi", B: "Mantı", C: "Kebap", D: "Lahmacun", E: "Pide", dogru: "A", aciklama: "Suşi, Japon yemeğidir." },
    { soru: "Hangisi bir İtalyan yemeği değildir?", A: "Taco", B: "Pizza", C: "Makarna", D: "Risotto", E: "Lazanya", dogru: "A", aciklama: "Taco, Meksika yemeğidir." },
    { soru: "Hangisi bir Çin yemeği değildir?", A: "Kebap", B: "Noodle", C: "Pekin Ördeği", D: "Dim Sum", E: "Spring Roll", dogru: "A", aciklama: "Kebap, Türk ve Orta Doğu mutfağına aittir." },
    { soru: "Hangisi bir Meksika yemeği değildir?", A: "Suşi", B: "Taco", C: "Burrito", D: "Enchilada", E: "Quesadilla", dogru: "A", aciklama: "Suşi, Japon yemeğidir." }
];
const hayvanSorulari = [
    { soru: "Dünyanın en büyük hayvanı hangisidir?", A: "Mavi Balina", B: "Fil", C: "Zürafa", D: "Köpekbalığı", E: "Kalamar", dogru: "A", aciklama: "Mavi balina, 30 metre ve 200 ton ağırlığa ulaşabilir." },
    { soru: "En hızlı kara hayvanı hangisidir?", A: "Çita", B: "Aslan", C: "Tavşan", D: "At", E: "Kanguru", dogru: "A", aciklama: "Çita, 120 km/s hıza ulaşabilir." },
    { soru: "Hangisi uçabilen bir memelidir?", A: "Yarasa", B: "Penguen", C: "Devekuşu", D: "Tavuk", E: "Kivi", dogru: "A", aciklama: "Yarasa, uçabilen tek memelidir." },
    { soru: "Zürafaların kaç boyun omuru vardır?", A: "7", B: "5", C: "10", D: "15", E: "20", dogru: "A", aciklama: "Zürafaların da insanlar gibi 7 boyun omuru vardır, sadece daha uzundur." },
    { soru: "Hangi hayvan 'ormanın kralı' olarak bilinir?", A: "Aslan", B: "Kaplan", C: "Ayı", D: "Kurt", E: "Fil", dogru: "A", aciklama: "Aslan, görkemli yelesiyle 'ormanın kralı' unvanını almıştır." },
    { soru: "Penguenler hangi yarım kürede yaşar?", A: "Güney", B: "Kuzey", C: "Her ikisi", D: "Ekvator", E: "Kutuplar", dogru: "A", aciklama: "Penguenler sadece Güney Yarım Küre'de yaşar." },
    { soru: "Kangurular hangi kıtada yaşar?", A: "Avustralya", B: "Afrika", C: "Asya", D: "Amerika", E: "Avrupa", dogru: "A", aciklama: "Kangurular Avustralya'ya özgüdür." },
    { soru: "Hangisi bir sürüngen değildir?", A: "Kurbağa", B: "Yılan", C: "Kertenkele", D: "Timsah", E: "Kaplumbağa", dogru: "A", aciklama: "Kurbağa iki yaşamlıdır (amfibi)." },
    { soru: "Hangi hayvan renk değiştirebilir?", A: "Bukalemun", B: "Kurbağa", C: "Yılan", D: "Balık", E: "Kelebek", dogru: "A", aciklama: "Bukalemunlar kamuflaj için renk değiştirir." },
    { soru: "En uzun yaşayan hayvan hangisidir?", A: "Kaplumbağa", B: "Fil", C: "Balina", D: "İnsan", E: "Köpekbalığı", dogru: "A", aciklama: "Dev kara kaplumbağaları 150-200 yıl yaşayabilir." },
    { soru: "Hangisi bir memeli hayvan değildir?", A: "Yılan", B: "Balina", C: "Yunus", D: "Fok", E: "Yarasa", dogru: "A", aciklama: "Yılan, sürüngendir." },
    { soru: "Hangisi bir kuş türü değildir?", A: "Yarasa", B: "Kartal", C: "Serçe", D: "Güvercin", E: "Penguen", dogru: "A", aciklama: "Yarasa, uçabilen bir memelidir." },
    { soru: "Hangisi bir balık türü değildir?", A: "Balina", B: "Hamsi", C: "Palamut", D: "Levrek", E: "Çipura", dogru: "A", aciklama: "Balina, memeli bir deniz canlısıdır." },
    { soru: "Hangisi bir böcek değildir?", A: "Örümcek", B: "Karınca", C: "Arı", D: "Kelebek", E: "Sinek", dogru: "A", aciklama: "Örümcekler örümceğimsiler sınıfındadır (8 bacak)." },
    { soru: "Hangisi etobur (etçil) bir hayvan değildir?", A: "İnek", B: "Aslan", C: "Kaplan", D: "Kurt", E: "Kartal", dogru: "A", aciklama: "İnek otoburdur (otçul)." },
    { soru: "Hangisi otobur (otçul) bir hayvan değildir?", A: "Kartal", B: "İnek", C: "Koyun", D: "Keçi", E: "At", dogru: "A", aciklama: "Kartal etoburdur." },
    { soru: "Hangisi hem et hem ot yiyen (hepçil) bir hayvandır?", A: "Ayı", B: "Aslan", C: "İnek", D: "Kartal", E: "Köpekbalığı", dogru: "A", aciklama: "Ayılar hem et hem de bitki yer." },
    { soru: "Hangisi gece aktif olan (noktürnal) bir hayvan değildir?", A: "Sincap", B: "Yarasa", C: "Baykuş", D: "Kirpi", E: "Rakun", dogru: "A", aciklama: "Sincaplar genellikle gündüz aktiftir." },
    { soru: "Hangisi kış uykusuna yatan bir hayvan değildir?", A: "Kutup Ayısı", B: "Boz Ayı", C: "Kirpi", D: "Yarasa", E: "Yer Sincabı", dogru: "A", aciklama: "Kutup ayıları kış uykusuna yatmaz." },
    { soru: "Hangisi göç eden bir kuş değildir?", A: "Penguen", B: "Leylek", C: "Kırlangıç", D: "Kaz", E: "Turna", dogru: "A", aciklama: "Penguenler göç etmez, yaşadıkları bölgede kalırlar." },
    { soru: "Hangisi bir sürü halinde yaşayan hayvan değildir?", A: "Kaplan", B: "Kurt", C: "Aslan", D: "Fil", E: "Zebra", dogru: "A", aciklama: "Kaplanlar genellikle yalnız yaşar." },
    { soru: "Hangisi bir yuva yapan hayvan değildir?", A: "Guguk Kuşu", B: "Leylek", C: "Kırlangıç", D: "Serçe", E: "Kartal", dogru: "A", aciklama: "Guguk kuşu, yumurtalarını başka kuşların yuvalarına bırakır." },
    { soru: "Hangisi zehirli bir yılan değildir?", A: "Piton", B: "Kobra", C: "Engerek", D: "Mamba", E: "Çıngıraklı Yılan", dogru: "A", aciklama: "Pitonlar zehirsizdir, avlarını sararak boğar." },
    { soru: "Hangisi bir köpek ırkı değildir?", A: "Van Kedisi", B: "Golden Retriever", C: "Alman Kurdu", D: "Husky", E: "Bulldog", dogru: "A", aciklama: "Van Kedisi, bir kedi ırkıdır." },
    { soru: "Hangisi bir kedi ırkı değildir?", A: "Husky", B: "Van Kedisi", C: "Siyam", D: "Persian", E: "British Shorthair", dogru: "A", aciklama: "Husky, bir köpek ırkıdır." },
    { soru: "Hangisi bir at türü değildir?", A: "Zebra", B: "Arap Atı", C: "İngiliz Atı", D: "Midilli", E: "Friz Atı", dogru: "A", aciklama: "Zebra, atgiller ailesinden olsa da farklı bir türdür." },
    { soru: "Hangisi bir maymun türü değildir?", A: "Koala", B: "Goril", C: "Şempanze", D: "Orangutan", E: "Babun", dogru: "A", aciklama: "Koala, keseli bir memelidir." },
    { soru: "Hangisi bir balina türü değildir?", A: "Köpekbalığı", B: "Mavi Balina", C: "Kambur Balina", D: "İspermeçet Balinası", E: "Katil Balina", dogru: "A", aciklama: "Köpekbalığı, balık sınıfındandır." },
    { soru: "Hangisi bir köpekbalığı türü değildir?", A: "Yunus", B: "Büyük Beyaz", C: "Çekiç Başlı", D: "Kaplan Köpekbalığı", E: "Balina Köpekbalığı", dogru: "A", aciklama: "Yunus, memelidir." },
    { soru: "Hangisi bir yunus türü değildir?", A: "Orka (Katil Balina)", B: "Afalina", C: "Mutur", D: "Dönücü Yunus", E: "Hepsi yunustur", dogru: "A", aciklama: "Orka, yunusgiller ailesinin en büyük üyesidir." },
    { soru: "Hangisi bir fok türü değildir?", A: "Mors", B: "Deniz Aslanı", C: "Deniz Fili", D: "Leopar Foku", E: "Hepsi foktur", dogru: "A", aciklama: "Mors, foklarla akraba olsa da ayrı bir ailedir." },
    { soru: "Hangisi bir ayı türü değildir?", A: "Koala", B: "Boz Ayı", C: "Kutup Ayısı", D: "Panda", E: "Tembel Ayı", dogru: "A", aciklama: "Koala, keseli bir memelidir." },
    { soru: "Hangisi bir geyik türü değildir?", A: "Ren Geyiği", B: "Karaca", C: "Alageyik", D: "Sığın", E: "Antilop", dogru: "E", aciklama: "Antilop, geyikgiller değil, boynuzlugiller ailesindendir." },
    { soru: "Hangisi bir kemirgen değildir?", A: "Tavşan", B: "Fare", C: "Sıçan", D: "Sincap", E: "Kunduz", dogru: "A", aciklama: "Tavşanlar, kemirgenler değil, lagomorfa takımındandır." },
    { soru: "Hangisi bir sürüngen değildir?", A: "Semender", B: "Yılan", C: "Kertenkele", D: "Timsah", E: "Kaplumbağa", dogru: "A", aciklama: "Semender, iki yaşamlıdır (amfibi)." },
    { soru: "Hangisi bir iki yaşamlı (amfibi) değildir?", A: "Kertenkele", B: "Kurbağa", C: "Semender", D: "Semender", E: "Su Kurbağası", dogru: "A", aciklama: "Kertenkele, sürüngendir." },
    { soru: "Hangisi bir örümcek türü değildir?", A: "Akrep", B: "Tarantula", C: "Kara Dul", D: "Sıçrayan Örümcek", E: "Hepsi örümcektir", dogru: "A", aciklama: "Akrep, örümceğimsiler sınıfından olsa da farklı bir takımdır." },
    { soru: "Hangisi bir karınca türü değildir?", A: "Termit", B: "Ateş Karıncası", C: "Marangoz Karınca", D: "Firavun Karıncası", E: "Hepsi karıncadır", dogru: "A", aciklama: "Termitler, karıncalardan farklı bir takımdır." },
    { soru: "Hangisi bir arı türü değildir?", A: "Eşek Arısı", B: "Bal Arısı", C: "Bombus Arısı", D: "Marangoz Arı", E: "Hepsi arıdır", dogru: "A", aciklama: "Eşek arısı, arılarla akraba olsa da farklı bir ailedir." },
    { soru: "Hangisi bir kelebek türü değildir?", A: "Yusufçuk", B: "Kırlangıçkuyruk", C: "Monark", D: "Beyaz Lahana Kelebeği", E: "Hepsi kelebektir", dogru: "A", aciklama: "Yusufçuk, kelebeklerden farklı bir takımdır." }
];
const sporSorulari = [
    { soru: "FIFA Dünya Kupası'nı en çok kazanan ülke hangisidir?", A: "Brezilya", B: "Almanya", C: "İtalya", D: "Arjantin", E: "Fransa", dogru: "A", aciklama: "Brezilya 5 kez Dünya Kupası kazanmıştır." },
    { soru: "NBA'de en çok şampiyonluk kazanan takım hangisidir?", A: "Boston Celtics", B: "LA Lakers", C: "Chicago Bulls", D: "Golden State", E: "Miami Heat", dogru: "A", aciklama: "Boston Celtics 17 şampiyonluk kazanmıştır." },
    { soru: "Grand Slam turnuvaları kaç tanedir?", A: "4", B: "3", C: "5", D: "6", E: "2", dogru: "A", aciklama: "Avustralya Açık, Fransa Açık, Wimbledon, ABD Açık." },
    { soru: "Bir futbol maçı kaç dakikadır?", A: "90", B: "60", C: "80", D: "100", E: "120", dogru: "A", aciklama: "Futbol maçları 90 dakika oynanır." },
    { soru: "Michael Jordan kaç numaralı formayı giymiştir?", A: "23", B: "24", C: "32", D: "33", E: "45", dogru: "A", aciklama: "Michael Jordan 23 numaralı formasıyla ünlüdür." },
    { soru: "Tenis maçında 'love' ne demektir?", A: "0 sayı", B: "15 sayı", C: "30 sayı", D: "40 sayı", E: "Beraberlik", dogru: "A", aciklama: "Love, teniste sıfır demektir." },
    { soru: "Hangisi bir spor dalı değildir? (Olimpik olarak)", A: "Satranç", B: "Yüzme", C: "Atletizm", D: "Jimnastik", E: "Boks", dogru: "A", aciklama: "Satranç Olimpiyatlarda yer almaz." },
    { soru: "Usain Bolt hangi dalda rekor sahibidir?", A: "100 metre", B: "200 metre", C: "400 metre", D: "800 metre", E: "Maraton", dogru: "A", aciklama: "Usain Bolt, 100m ve 200m dünya rekortmenidir." },
    { soru: "Hangisi bir basketbol terimi değildir?", A: "Korner", B: "Smaç", C: "Turnike", D: "Blok", E: "Hücum Faul", dogru: "A", aciklama: "Korner futbol terimidir." },
    { soru: "Olimpiyat halkaları kaç kıtayı temsil eder?", A: "5", B: "4", C: "6", D: "7", E: "3", dogru: "A", aciklama: "5 halka, 5 kıtayı temsil eder." },
    { soru: "Hangisi bir futbol pozisyonu değildir?", A: "Pivot", B: "Kaleci", C: "Defans", D: "Orta Saha", E: "Forvet", dogru: "A", aciklama: "Pivot basketbol terimidir." },
    { soru: "Penaltı noktası kaleden kaç metre uzaktadır?", A: "11", B: "9", C: "10", D: "12", E: "13", dogru: "A", aciklama: "Penaltı noktası kale çizgisinden 11 metre uzaktadır." },
    { soru: "NBA'de bir periyot kaç dakikadır?", A: "12", B: "10", C: "15", D: "20", E: "8", dogru: "A", aciklama: "NBA'de periyotlar 12 dakikadır." },
    { soru: "Üç sayı çizgisi potadan kaç metre uzaktadır? (NBA)", A: "7.24", B: "6.25", C: "6.75", D: "7.50", E: "8.00", dogru: "A", aciklama: "NBA'de üçlük çizgisi 7.24 metredir." },
    { soru: "Wimbledon hangi zeminde oynanır?", A: "Çim", B: "Toprak", C: "Sert", D: "Halı", E: "Kum", dogru: "A", aciklama: "Wimbledon çim zeminde oynanan tek Grand Slam'dir." },
    { soru: "Rafael Nadal hangi zeminde en başarılıdır?", A: "Toprak", B: "Çim", C: "Sert", D: "Halı", E: "Hepsi eşit", dogru: "A", aciklama: "Nadal 'Toprağın Kralı' olarak bilinir." },
    { soru: "Voleybolda bir takım kaç oyuncudan oluşur? (Sahada)", A: "6", B: "5", C: "7", D: "4", E: "8", dogru: "A", aciklama: "Voleybolda sahada 6 oyuncu bulunur." },
    { soru: "Hentbolda bir takım kaç oyuncudan oluşur? (Sahada)", A: "7", B: "6", C: "5", D: "8", E: "11", dogru: "A", aciklama: "Hentbolda sahada 6 saha oyuncusu + 1 kaleci = 7 oyuncu." },
    { soru: "Buz hokeyinde bir takım kaç oyuncudan oluşur? (Sahada)", A: "6", B: "5", C: "7", D: "4", E: "11", dogru: "A", aciklama: "Buz hokeyinde sahada 5 oyuncu + 1 kaleci = 6 oyuncu." },
    { soru: "Formula 1'de en çok şampiyonluk kazanan takım hangisidir?", A: "Ferrari", B: "Mercedes", C: "Red Bull", D: "McLaren", E: "Williams", dogru: "A", aciklama: "Ferrari, 16 markalar şampiyonluğu kazanmıştır." },
    { soru: "Tour de France bisiklet yarışı kaç gün sürer?", A: "21", B: "15", C: "30", D: "10", E: "7", dogru: "A", aciklama: "Tour de France, 21 etap ve 2 dinlenme günüyle yaklaşık 23 gün sürer." },
    { soru: "Yüzmede en hızlı stil hangisidir?", A: "Serbest (Crawl)", B: "Kelebek", C: "Sırtüstü", D: "Kurbağalama", E: "Hepsi eşit", dogru: "A", aciklama: "Serbest stil (crawl) en hızlı yüzme stilidir." },
    { soru: "Hangisi bir atletizm dalı değildir?", A: "Trambolin", B: "100 metre", C: "Maraton", D: "Cirit Atma", E: "Yüksek Atlama", dogru: "A", aciklama: "Trambolin, jimnastik dalıdır." },
    { soru: "Hangisi bir jimnastik aleti değildir?", A: "Halter", B: "Barfiks", C: "Denge Kalası", D: "Halka", E: "Kulplu Beygir", dogru: "A", aciklama: "Halter, ayrı bir spor dalıdır." },
    { soru: "Hangisi bir dövüş sporu değildir?", A: "Kriket", B: "Boks", C: "Judo", D: "Karate", E: "Tekvando", dogru: "A", aciklama: "Kriket, bir takım sporudur." },
    { soru: "Hangisi bir kış sporu değildir?", A: "Sörf", B: "Kayak", C: "Snowboard", D: "Buz Hokeyi", E: "Körling", dogru: "A", aciklama: "Sörf, yaz sporudur." },
    { soru: "Hangisi bir su sporu değildir?", A: "Dağcılık", B: "Yüzme", C: "Su Topu", D: "Kürek", E: "Yelken", dogru: "A", aciklama: "Dağcılık, kara sporudur." },
    { soru: "Hangisi bir ekstrem spor değildir?", A: "Satranç", B: "Bungee Jumping", C: "Paraşütle Atlama", D: "Dağ Bisikleti", E: "Kaya Tırmanışı", dogru: "A", aciklama: "Satranç, zeka sporudur." },
    { soru: "Hangisi bir takım sporu değildir?", A: "Tenis (Tekler)", B: "Futbol", C: "Basketbol", D: "Voleybol", E: "Hentbol", dogru: "A", aciklama: "Tekler tenis bireysel bir spordur." },
    { soru: "Hangisi bir bireysel spor değildir?", A: "Voleybol", B: "Tenis", C: "Yüzme", D: "Atletizm", E: "Golf", dogru: "A", aciklama: "Voleybol takım sporudur." },
    { soru: "Hangisi bir olimpiyat sporu değildir?", A: "Bilardo", B: "Okçuluk", C: "Eskrim", D: "Halter", E: "Güreş", dogru: "A", aciklama: "Bilardo, Olimpiyat programında yer almaz." },
    { soru: "Olimpiyat Oyunları kaç yılda bir düzenlenir?", A: "4", B: "2", C: "3", D: "5", E: "6", dogru: "A", aciklama: "Olimpiyatlar 4 yılda bir düzenlenir." },
    { soru: "İlk modern Olimpiyat Oyunları hangi yıl düzenlenmiştir?", A: "1896", B: "1900", C: "1892", D: "1904", E: "1888", dogru: "A", aciklama: "İlk modern Olimpiyatlar 1896'da Atina'da düzenlenmiştir." },
    { soru: "Türkiye'nin futbolda en büyük uluslararası başarısı nedir?", A: "2002 Dünya Kupası 3.lüğü", B: "2008 Avrupa Şampiyonası 3.lüğü", C: "2003 Konfederasyon Kupası 3.lüğü", D: "2000 UEFA Kupası Şampiyonluğu", E: "2012 Olimpiyat 2.liği", dogru: "A", aciklama: "Türkiye, 2002 Dünya Kupası'nda 3. olmuştur." },
    { soru: "Galatasaray'ın 2000 yılında kazandığı Avrupa kupası hangisidir?", A: "UEFA Kupası", B: "Şampiyonlar Ligi", C: "Kupa Galipleri Kupası", D: "Süper Kupa", E: "Konferans Ligi", dogru: "A", aciklama: "Galatasaray, 2000'de UEFA Kupası'nı kazanmıştır." },
    { soru: "Fenerbahçe'nin 2023 yılında kazandığı Avrupa kupası hangisidir?", A: "Konferans Ligi", B: "UEFA Kupası", C: "Şampiyonlar Ligi", D: "Süper Kupa", E: "Kupa Galipleri", dogru: "A", aciklama: "Fenerbahçe, 2023'te Konferans Ligi'ni kazanmıştır." },
    { soru: "Hangisi bir Formula 1 pilotu değildir?", A: "Valentino Rossi", B: "Lewis Hamilton", C: "Max Verstappen", D: "Charles Leclerc", E: "Fernando Alonso", dogru: "A", aciklama: "Valentino Rossi, MotoGP pilotudur." },
    { soru: "Hangisi bir MotoGP pilotu değildir?", A: "Lewis Hamilton", B: "Valentino Rossi", C: "Marc Marquez", D: "Francesco Bagnaia", E: "Jorge Lorenzo", dogru: "A", aciklama: "Lewis Hamilton, Formula 1 pilotudur." },
    { soru: "Hangisi bir NBA takımı değildir?", A: "Real Madrid", B: "LA Lakers", C: "Boston Celtics", D: "Chicago Bulls", E: "Miami Heat", dogru: "A", aciklama: "Real Madrid, basketbol takımı olsa da NBA'de değil, EuroLeague'dedir." },
    { soru: "Hangisi bir futbol stadyumu değildir?", A: "Madison Square Garden", B: "Camp Nou", C: "Wembley", D: "Maracana", E: "Allianz Arena", dogru: "A", aciklama: "Madison Square Garden, basketbol ve konser salonudur." }
];
const teknolojiSorulari = [
    { soru: "iPhone hangi firmanın ürünüdür?", A: "Apple", B: "Samsung", C: "Xiaomi", D: "Huawei", E: "Google", dogru: "A", aciklama: "iPhone, Apple'ın akıllı telefon serisidir." },
    { soru: "Android hangi şirkete aittir?", A: "Google", B: "Apple", C: "Microsoft", D: "Samsung", E: "Amazon", dogru: "A", aciklama: "Android, Google tarafından geliştirilen işletim sistemidir." },
    { soru: "Hangisi bir sosyal medya platformu değildir?", A: "Adobe", B: "Instagram", C: "Twitter", D: "Facebook", E: "TikTok", dogru: "A", aciklama: "Adobe, yazılım şirketidir." },
    { soru: "Bluetooth adını nereden almıştır?", A: "Viking Kralı", B: "Bilim Kurgu Filminden", C: "Bir Şirketten", D: "Bir Hayvandan", E: "Bir Şehirden", dogru: "A", aciklama: "Bluetooth, Viking Kralı Harald Bluetooth'tan adını alır." },
    { soru: "Hangisi bir programlama dili değildir?", A: "HTML", B: "Python", C: "Java", D: "C++", E: "JavaScript", dogru: "A", aciklama: "HTML işaretleme dilidir, programlama dili değildir." },
    { soru: "İlk iPhone hangi yıl piyasaya sürülmüştür?", A: "2007", B: "2005", C: "2008", D: "2010", E: "2012", dogru: "A", aciklama: "İlk iPhone, 2007'de Steve Jobs tarafından tanıtılmıştır." },
    { soru: "Hangisi bir bulut depolama hizmetidir?", A: "Google Drive", B: "Microsoft Word", C: "Adobe Photoshop", D: "VLC", E: "WinRAR", dogru: "A", aciklama: "Google Drive, bulut depolama hizmetidir." },
    { soru: "Wi-Fi neyin kısaltmasıdır?", A: "Wireless Fidelity", B: "Wireless Fiber", C: "Wide Frequency", D: "Wireless Finder", E: "Wired Fiber", dogru: "A", aciklama: "Wi-Fi, Wireless Fidelity'nin kısaltmasıdır." },
    { soru: "Hangisi bir işletim sistemi değildir?", A: "Python", B: "Windows", C: "macOS", D: "Linux", E: "Android", dogru: "A", aciklama: "Python bir programlama dilidir." },
    { soru: "Hangisi bir arama motoru değildir?", A: "Facebook", B: "Google", C: "Bing", D: "Yahoo", E: "Yandex", dogru: "A", aciklama: "Facebook sosyal medya platformudur." },
    { soru: "Hangisi bir web tarayıcısı değildir?", A: "Spotify", B: "Chrome", C: "Firefox", D: "Safari", E: "Edge", dogru: "A", aciklama: "Spotify, müzik dinleme platformudur." },
    { soru: "Hangisi bir e-posta sağlayıcısı değildir?", A: "WhatsApp", B: "Gmail", C: "Outlook", D: "Yahoo Mail", E: "ProtonMail", dogru: "A", aciklama: "WhatsApp, anlık mesajlaşma uygulamasıdır." },
    { soru: "Hangisi bir bilgisayar donanımı değildir?", A: "Windows", B: "RAM", C: "CPU", D: "SSD", E: "Anakart", dogru: "A", aciklama: "Windows, işletim sistemidir." },
    { soru: "CPU neyin kısaltmasıdır?", A: "Central Processing Unit", B: "Computer Power Unit", C: "Core Program Utility", D: "Central Program Unit", E: "Computer Processing Unit", dogru: "A", aciklama: "CPU = Central Processing Unit (Merkezi İşlem Birimi)." },
    { soru: "RAM ne işe yarar?", A: "Geçici veri depolama", B: "Kalıcı depolama", C: "Grafik işleme", D: "Ses işleme", E: "Ağ bağlantısı", dogru: "A", aciklama: "RAM, bilgisayarın geçici hafızasıdır." },
    { soru: "SSD'nin avantajı nedir?", A: "HDD'den daha hızlıdır", B: "HDD'den daha ucuzdur", C: "HDD'den daha fazla kapasitelidir", D: "HDD'den daha dayanıklıdır", E: "Hepsi", dogru: "A", aciklama: "SSD'ler, hareketli parça olmadığı için HDD'lerden çok daha hızlıdır." },
    { soru: "Hangisi bir ekran kartı üreticisi değildir?", A: "Intel Core", B: "NVIDIA", C: "AMD", D: "Intel Arc", E: "Hepsi üreticidir", dogru: "A", aciklama: "Intel Core, işlemci serisidir." },
    { soru: "Hangisi bir işlemci üreticisi değildir?", A: "NVIDIA", B: "Intel", C: "AMD", D: "Apple", E: "Qualcomm", dogru: "A", aciklama: "NVIDIA, ekran kartı üreticisidir." },
    { soru: "USB neyin kısaltmasıdır?", A: "Universal Serial Bus", B: "Ultra Speed Bandwidth", C: "United System Bridge", D: "Universal System Backup", E: "Ultra Storage Base", dogru: "A", aciklama: "USB = Universal Serial Bus." },
    { soru: "Hangisi bir görüntü formatı değildir?", A: "MP3", B: "JPEG", C: "PNG", D: "GIF", E: "BMP", dogru: "A", aciklama: "MP3, ses formatıdır." },
    { soru: "Hangisi bir ses formatı değildir?", A: "JPEG", B: "MP3", C: "WAV", D: "FLAC", E: "AAC", dogru: "A", aciklama: "JPEG, görüntü formatıdır." },
    { soru: "Hangisi bir video formatı değildir?", A: "PDF", B: "MP4", C: "AVI", D: "MKV", E: "MOV", dogru: "A", aciklama: "PDF, belge formatıdır." },
    { soru: "Hangisi bir yapay zeka asistanı değildir?", A: "Siri", B: "Alexa", C: "Google Assistant", D: "Cortana", E: "Photoshop", dogru: "E", aciklama: "Photoshop, grafik tasarım programıdır." },
    { soru: "Hangisi bir sosyal medya fenomeni değildir?", A: "Bill Gates", B: "Khaby Lame", C: "Charli D'Amelio", D: "MrBeast", E: "Addison Rae", dogru: "A", aciklama: "Bill Gates, iş insanı ve hayırseverdir." },
    { soru: "Hangisi bir kripto para birimi değildir?", A: "PayPal", B: "Bitcoin", C: "Ethereum", D: "Dogecoin", E: "Ripple", dogru: "A", aciklama: "PayPal, ödeme sistemidir." },
    { soru: "Blockchain teknolojisi nedir?", A: "Dağıtık defter teknolojisi", B: "Merkezi veri tabanı", C: "Bulut depolama", D: "Yapay zeka algoritması", E: "Sanal gerçeklik", dogru: "A", aciklama: "Blockchain, verilerin zincirleme ve dağıtık olarak saklandığı bir teknolojidir." },
    { soru: "Hangisi bir Tesla modeli değildir?", A: "Mustang", B: "Model S", C: "Model 3", D: "Model X", E: "Model Y", dogru: "A", aciklama: "Mustang, Ford'un modelidir." },
    { soru: "Hangisi bir elektrikli araç üreticisi değildir?", A: "Ferrari (yakın zamana kadar)", B: "Tesla", C: "Rivian", D: "Lucid", E: "NIO", dogru: "A", aciklama: "Ferrari, elektrikli araç üretimine yeni başlamıştır." },
    { soru: "Hangisi bir uzay şirketi değildir?", A: "Boeing (yolcu uçağı)", B: "SpaceX", C: "Blue Origin", D: "Virgin Galactic", E: "NASA", dogru: "A", aciklama: "Boeing, öncelikle yolcu uçağı üreticisidir." },
    { soru: "Hangisi bir bilgisayar virüsü türü değildir?", A: "Cookie", B: "Truva Atı", C: "Solucan", D: "Fidye Yazılımı", E: "Spyware", dogru: "A", aciklama: "Cookie'ler, web siteleri tarafından depolanan küçük veri dosyalarıdır." },
    { soru: "Hangisi bir siber güvenlik terimi değildir?", A: "Firewall (Güvenlik Duvarı)", B: "Phishing", C: "DDoS", D: "Encryption", E: "Cookie", dogru: "E", aciklama: "Cookie'ler genellikle zararsızdır." },
    { soru: "Hangisi bir yazılım lisansı türü değildir?", A: "Donanım", B: "Açık Kaynak", C: "Freeware", D: "Shareware", E: "Ticari", dogru: "A", aciklama: "Donanım, fiziksel bileşenlerdir." },
    { soru: "Hangisi bir kod editörü değildir?", A: "Excel", B: "VS Code", C: "Sublime Text", D: "Atom", E: "Notepad++", dogru: "A", aciklama: "Excel, hesap tablosu programıdır." },
    { soru: "Hangisi bir veri tabanı yönetim sistemi değildir?", A: "Apache", B: "MySQL", C: "PostgreSQL", D: "MongoDB", E: "Oracle", dogru: "A", aciklama: "Apache, web sunucusu yazılımıdır." },
    { soru: "Hangisi bir yapay zeka alanı değildir?", A: "Muhasebe", B: "Makine Öğrenmesi", C: "Derin Öğrenme", D: "Doğal Dil İşleme", E: "Bilgisayarlı Görü", dogru: "A", aciklama: "Muhasebe, işletme alanıdır." },
    { soru: "Hangisi bir robot türü değildir?", A: "Android", B: "Endüstriyel Robot", C: "Cobot", D: "Drone", E: "Hepsi robot türüdür", dogru: "E", aciklama: "Android (insansı robot), endüstriyel robot, cobot ve drone robot türleridir." },
    { soru: "Hangisi bir sanal gerçeklik (VR) gözlüğü değildir?", A: "Kindle", B: "Oculus Quest", C: "HTC Vive", D: "PlayStation VR", E: "Valve Index", dogru: "A", aciklama: "Kindle, e-kitap okuyucudur." },
    { soru: "Hangisi bir akıllı ev cihazı değildir?", A: "Normal Anahtar", B: "Akıllı Priz", C: "Akıllı Ampul", D: "Akıllı Termostat", E: "Akıllı Kilit", dogru: "A", aciklama: "Normal anahtar, akıllı değildir." },
    { soru: "Hangisi bir giyilebilir teknoloji ürünü değildir?", A: "Laptop", B: "Akıllı Saat", C: "Fitness Takipçisi", D: "Akıllı Gözlük", E: "Akıllı Yüzük", dogru: "A", aciklama: "Laptop, taşınabilir olsa da giyilebilir değildir." },
    { soru: "Hangisi bir oyun konsolu değildir?", A: "iPad", B: "PlayStation", C: "Xbox", D: "Nintendo Switch", E: "Steam Deck", dogru: "A", aciklama: "iPad, tablet bilgisayardır." }
];
const genelkulturSorulari = [
    { soru: "Türkiye'nin başkenti neresidir?", A: "Ankara", B: "İstanbul", C: "İzmir", D: "Bursa", E: "Antalya", dogru: "A", aciklama: "Ankara, 1923'ten beri Türkiye'nin başkentidir." },
    { soru: "Dünyanın en büyük okyanusu hangisidir?", A: "Pasifik", B: "Atlas", C: "Hint", D: "Arktik", E: "Güney", dogru: "A", aciklama: "Pasifik Okyanusu 165 milyon km² alana sahiptir." },
    { soru: "En yüksek dağ hangisidir?", A: "Everest", B: "K2", C: "Kangchenjunga", D: "Lhotse", E: "Makalu", dogru: "A", aciklama: "Everest, 8.848 metre yüksekliğindedir." },
    { soru: "İstanbul'un fethi hangi yılda olmuştur?", A: "1453", B: "1451", C: "1457", D: "1461", E: "1473", dogru: "A", aciklama: "Fatih Sultan Mehmet, 1453'te İstanbul'u fethetmiştir." },
    { soru: "Türkiye Cumhuriyeti hangi yılda kurulmuştur?", A: "1923", B: "1920", C: "1921", D: "1922", E: "1924", dogru: "A", aciklama: "29 Ekim 1923'te Cumhuriyet ilan edilmiştir." },
    { soru: "İlk Türk devleti hangisidir?", A: "Hunlar", B: "Göktürkler", C: "Uygurlar", D: "Selçuklular", E: "Osmanlılar", dogru: "A", aciklama: "Asya Hun İmparatorluğu, bilinen ilk Türk devletidir." },
    { soru: "Bir yılda kaç ay vardır?", A: "12", B: "10", C: "11", D: "13", E: "14", dogru: "A", aciklama: "Bir yıl 12 aydan oluşur." },
    { soru: "Hangi gezegen Güneş'e en yakındır?", A: "Merkür", B: "Venüs", C: "Dünya", D: "Mars", E: "Jüpiter", dogru: "A", aciklama: "Merkür, Güneş'e en yakın gezegendir." },
    { soru: "2+2 kaçtır?", A: "4", B: "3", C: "5", D: "6", E: "7", dogru: "A", aciklama: "2+2=4 eder." },
    { soru: "Atatürk hangi yıl doğmuştur?", A: "1881", B: "1885", C: "1890", D: "1900", E: "1875", dogru: "A", aciklama: "Mustafa Kemal Atatürk, 1881'de Selanik'te doğmuştur." },
    { soru: "Türkiye'nin en kalabalık şehri hangisidir?", A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa", E: "Antalya", dogru: "A", aciklama: "İstanbul, Türkiye'nin en kalabalık şehridir." },
    { soru: "Dünyanın en kalabalık ülkesi hangisidir?", A: "Hindistan", B: "Çin", C: "ABD", D: "Endonezya", E: "Brezilya", dogru: "A", aciklama: "Hindistan, 2023 itibariyle dünyanın en kalabalık ülkesidir." },
    { soru: "En uzun nehir hangisidir?", A: "Nil", B: "Amazon", C: "Yangtze", D: "Mississippi", E: "Sarı Irmak", dogru: "A", aciklama: "Nil Nehri, 6.650 km ile dünyanın en uzun nehridir." },
    { soru: "En büyük kıta hangisidir?", A: "Asya", B: "Afrika", C: "Kuzey Amerika", D: "Güney Amerika", E: "Avrupa", dogru: "A", aciklama: "Asya kıtası, 44 milyon km² alanıyla en büyüktür." },
    { soru: "Türkiye'nin en yüksek dağı hangisidir?", A: "Ağrı Dağı", B: "Erciyes", C: "Süphan", D: "Kaçkar", E: "Uludağ", dogru: "A", aciklama: "Ağrı Dağı, 5.137 metre ile Türkiye'nin en yüksek dağıdır." },
    { soru: "Türkiye'nin en büyük gölü hangisidir?", A: "Van Gölü", B: "Tuz Gölü", C: "Beyşehir Gölü", D: "Eğirdir Gölü", E: "İznik Gölü", dogru: "A", aciklama: "Van Gölü, 3.755 km² alanıyla Türkiye'nin en büyük gölüdür." },
    { soru: "Hangisi bir Türk büyüğü değildir?", A: "Napolyon", B: "Atatürk", C: "Fatih Sultan Mehmet", D: "Kanuni Sultan Süleyman", E: "Yavuz Sultan Selim", dogru: "A", aciklama: "Napolyon Bonapart, Fransız komutan ve imparatordur." },
    { soru: "Hangisi bir antik dünya harikası değildir?", A: "Kolezyum", B: "Babil'in Asma Bahçeleri", C: "İskenderiye Feneri", D: "Rodos Heykeli", E: "Zeus Heykeli", dogru: "A", aciklama: "Kolezyum, antik dünya harikaları listesinde değildir." },
    { soru: "Birleşmiş Milletler'in resmi dilleri kaç tanedir?", A: "6", B: "5", C: "4", D: "7", E: "3", dogru: "A", aciklama: "BM'nin 6 resmi dili vardır: İngilizce, Fransızca, İspanyolca, Rusça, Çince, Arapça." },
    { soru: "Nobel Ödülleri hangi ülkede verilir? (Barış Ödülü hariç)", A: "İsveç", B: "Norveç", C: "Danimarka", D: "Finlandiya", E: "İngiltere", dogru: "A", aciklama: "Nobel Barış Ödülü Norveç'te, diğerleri İsveç'te verilir." },
    { soru: "İstiklal Marşı'nın yazarı kimdir?", A: "Mehmet Akif Ersoy", B: "Osman Zeki Üngör", C: "Yahya Kemal", D: "Namık Kemal", E: "Ziya Gökalp", dogru: "A", aciklama: "İstiklal Marşı'nı Mehmet Akif Ersoy yazmıştır." },
    { soru: "İstiklal Marşı'nın bestecisi kimdir?", A: "Osman Zeki Üngör", B: "Mehmet Akif Ersoy", C: "Cemal Reşit Rey", D: "Ahmet Adnan Saygun", E: "Ulvi Cemal Erkin", dogru: "A", aciklama: "İstiklal Marşı'nı Osman Zeki Üngör bestelemiştir." },
    { soru: "Hangisi bir Türk şair değildir?", A: "Shakespeare", B: "Yunus Emre", C: "Fuzuli", D: "Baki", E: "Nedim", dogru: "A", aciklama: "Shakespeare, İngiliz şair ve oyun yazarıdır." },
    { soru: "Hangisi bir Türk yazar değildir?", A: "Dostoyevski", B: "Yaşar Kemal", C: "Orhan Pamuk", D: "Sabahattin Ali", E: "Oğuz Atay", dogru: "A", aciklama: "D