const marvelSorulari = [
    { soru: "Iron Man'in gerçek adı nedir?", A: "Tony Stark", B: "Steve Rogers", C: "Bruce Banner", D: "Thor Odinson", E: "Clint Barton", dogru: "A", aciklama: "Tony Stark, milyarder iş adamı ve dahi mucittir." },
    { soru: "Thor'un çekicinin adı nedir?", A: "Mjolnir", B: "Stormbreaker", C: "Gungnir", D: "Hofund", E: "Jarnbjorn", dogru: "A", aciklama: "Mjolnir, sadece 'layık olan' tarafından kaldırılabilir." },
    { soru: "Spider-Man'in gerçek adı nedir?", A: "Peter Parker", B: "Miles Morales", C: "Ben Reilly", D: "Miguel O'Hara", E: "Gwen Stacy", dogru: "A", aciklama: "Peter Parker, radyoaktif bir örümcek tarafından ısırılmıştır." },
    { soru: "Captain America'nın kalkanı hangi metalden yapılmıştır?", A: "Vibranyum", B: "Adamantium", C: "Uru", D: "Titanyum", E: "Karbon", dogru: "A", aciklama: "Kalkan, Wakanda'dan gelen Vibranyum alaşımıdır." },
    { soru: "Hulk'ın gerçek adı nedir?", A: "Bruce Banner", B: "Bruce Wayne", C: "Clark Kent", D: "Peter Parker", E: "Tony Stark", dogru: "A", aciklama: "Dr. Bruce Banner, gama radyasyonu sonucu Hulk'a dönüşür." },
    { soru: "Black Widow'un gerçek adı nedir?", A: "Natasha Romanoff", B: "Yelena Belova", C: "Wanda Maximoff", D: "Carol Danvers", E: "Hope van Dyne", dogru: "A", aciklama: "Natasha Romanoff, eski bir KGB ajanıdır." },
    { soru: "Doctor Strange'in unvanı nedir?", A: "Yüce Büyücü", B: "Büyücü", C: "Sihirbaz", D: "Mistik", E: "Koruyucu", dogru: "A", aciklama: "Doctor Strange, Yüce Büyücü (Sorcerer Supreme) unvanını taşır." },
    { soru: "Loki'nin gerçek ırkı nedir?", A: "Buz Devi", B: "Asgardlı", C: "Karanlık Elf", D: "Cüce", E: "Vanir", dogru: "A", aciklama: "Loki, Jotunheim'dan bir Buz Devidir, Odin tarafından evlat edinilmiştir." },
    { soru: "Thanos hangi taşları toplamaya çalışmıştır?", A: "Sonsuzluk Taşları", B: "Zaman Taşları", C: "Güç Taşları", D: "Ruh Taşları", E: "Gerçeklik Taşları", dogru: "A", aciklama: "6 Sonsuzluk Taşı: Zihin, Ruh, Zaman, Gerçeklik, Güç, Uzay." },
    { soru: "Black Panther'in ülkesi neresidir?", A: "Wakanda", B: "Sokovia", C: "Latveria", D: "Genosha", E: "Atlantis", dogru: "A", aciklama: "Wakanda, teknolojik olarak ileri ve Vibranyum zengini bir Afrika ülkesidir." },
    { soru: "Ant-Man'in gerçek adı nedir?", A: "Scott Lang", B: "Hank Pym", C: "Hope van Dyne", D: "Bill Foster", E: "Eric O'Grady", dogru: "A", aciklama: "Scott Lang, Hank Pym'in teknolojisiyle Ant-Man olmuştur." },
    { soru: "Vision'ın alnındaki taş hangisidir?", A: "Zihin Taşı", B: "Ruh Taşı", C: "Zaman Taşı", D: "Gerçeklik Taşı", E: "Güç Taşı", dogru: "A", aciklama: "Vision, Zihin Taşı sayesinde bilinç kazanmıştır." },
    { soru: "Hawkeye'ın gerçek adı nedir?", A: "Clint Barton", B: "Oliver Queen", C: "Roy Harper", D: "John Diggle", E: "Malcolm Merlyn", dogru: "A", aciklama: "Clint Barton, dünyanın en iyi okçularından biridir." },
    { soru: "Scarlet Witch'in gerçek adı nedir?", A: "Wanda Maximoff", B: "Pietro Maximoff", C: "Jean Grey", D: "Lorna Dane", E: "Ororo Munroe", dogru: "A", aciklama: "Wanda Maximoff, Kaos Büyüsü kullanabilen güçlü bir mutanttır." },
    { soru: "Winter Soldier'ın gerçek adı nedir?", A: "Bucky Barnes", B: "Steve Rogers", C: "Sam Wilson", D: "John Walker", E: "Isaiah Bradley", dogru: "A", aciklama: "Bucky Barnes, Hydra tarafından beyni yıkanmıştır." },
    { soru: "Star-Lord'un gerçek adı nedir?", A: "Peter Quill", B: "Jason Quill", C: "Peter Parker", D: "Richard Rider", E: "Adam Warlock", dogru: "A", aciklama: "Peter Quill, Ravager'lar tarafından büyütülmüştür." },
    { soru: "Gamora hangi gezegendendir?", A: "Zehoberei", B: "Xandar", C: "Sakaar", D: "Vormir", E: "Knowhere", dogru: "A", aciklama: "Gamora, Thanos tarafından evlat edinilmiş Zehoberei'li bir savaşçıdır." },
    { soru: "Drax'ın lakabı nedir?", A: "Yok Edici", B: "Koruyucu", C: "Savaşçı", D: "Yıldız Lordu", E: "Koleksiyoncu", dogru: "A", aciklama: "Drax, 'Yok Edici' olarak bilinir." },
    { soru: "Groot hangi dildir?", A: "Grootça", B: "Ağaç Dili", C: "Flora", D: "Entish", E: "Botanik", dogru: "A", aciklama: "Groot sadece 'Ben Groot' der." },
    { soru: "Rocket hangi hayvandır?", A: "Rakun", B: "Sincap", C: "Fare", D: "Tavşan", E: "Kedi", dogru: "A", aciklama: "Rocket, genetik olarak değiştirilmiş bir rakundur." },
    { soru: "Nick Fury hangi organizasyonun lideridir?", A: "SHIELD", B: "HYDRA", C: "SWORD", D: "Avengers", E: "X-Men", dogru: "A", aciklama: "Nick Fury, SHIELD'in efsanevi lideridir." },
    { soru: "Thanos hangi gezegendendir?", A: "Titan", B: "Ego", C: "Xandar", D: "Sakaar", E: "Vormir", dogru: "A", aciklama: "Thanos, Titan gezegeninin son kurtulanıdır." },
    { soru: "Hangi Avengers filminde 'Endgame' alt başlığı kullanılmıştır?", A: "Avengers 4", B: "Avengers 3", C: "Avengers 5", D: "Avengers 2", E: "Avengers 1", dogru: "A", aciklama: "Avengers: Endgame, Infinity War'ın devamıdır." },
    { soru: "Captain Marvel'ın gerçek adı nedir?", A: "Carol Danvers", B: "Maria Rambeau", C: "Monica Rambeau", D: "Kamala Khan", E: "Jean Grey", dogru: "A", aciklama: "Carol Danvers, Captain Marvel'dır." },
    { soru: "Shang-Chi hangi silahı kullanır?", A: "On Halka", B: "Kılıç", C: "Kalkan", D: "Çekiç", E: "Yay", dogru: "A", aciklama: "Shang-Chi, efsanevi On Halka'yı kullanır." },
    { soru: "Eternals filmindeki lider karakter kimdir?", A: "Ajak", B: "Ikaris", C: "Sersi", D: "Thena", E: "Kingo", dogru: "A", aciklama: "Ajak, Eternals'ın ruhani lideridir." },
    { soru: "WandaVision dizisi hangi yıl geçmektedir?", A: "2023", B: "2024", C: "2025", D: "2022", E: "2021", dogru: "A", aciklama: "WandaVision, Endgame'den kısa süre sonra geçer." },
    { soru: "Loki dizisinde TVA neyin kısaltmasıdır?", A: "Time Variance Authority", B: "Time Vector Authority", C: "Temporal Variance Agency", D: "Time Voyage Administration", E: "Temporal Vector Agency", dogru: "A", aciklama: "TVA = Time Variance Authority (Zaman Değişkenliği Otoritesi)." },
    { soru: "Moon Knight'ın gerçek adı nedir?", A: "Hepsi (Marc Spector, Steven Grant, Jake Lockley)", B: "Marc Spector", C: "Steven Grant", D: "Jake Lockley", E: "Arthur Harrow", dogru: "A", aciklama: "Moon Knight, dissosiyatif kimlik bozukluğuna sahiptir." },
    { soru: "She-Hulk'un gerçek adı nedir?", A: "Jennifer Walters", B: "Jessica Jones", C: "Carol Danvers", D: "Natasha Romanoff", E: "Wanda Maximoff", dogru: "A", aciklama: "Jennifer Walters, Bruce Banner'ın kuzenidir." },
    { soru: "Deadpool'un gerçek adı nedir?", A: "Wade Wilson", B: "Wade Williams", C: "Wilson Fisk", D: "Wade Winston", E: "Slade Wilson", dogru: "A", aciklama: "Deadpool'un gerçek adı Wade Winston Wilson'dır." },
    { soru: "Daredevil'in gerçek adı nedir?", A: "Matt Murdock", B: "Matt Damon", C: "Matt Smith", D: "Matt LeBlanc", E: "Matt Dillon", dogru: "A", aciklama: "Matt Murdock, kör bir avukat ve geceleri Daredevil'dir." },
    { soru: "Punisher'ın gerçek adı nedir?", A: "Frank Castle", B: "John Wick", C: "Jack Reacher", D: "Jason Bourne", E: "James Bond", dogru: "A", aciklama: "Frank Castle, ailesinin intikamını alan bir kanunsuzdur." },
    { soru: "Blade'in gerçek adı nedir?", A: "Eric Brooks", B: "Blade Smith", C: "John Blade", D: "Michael Morbius", E: "Hannibal King", dogru: "A", aciklama: "Eric Brooks, yarı vampir yarı insan bir avcıdır." },
    { soru: "Ghost Rider'ın gerçek adı nedir? (Johnny Blaze)", A: "Johnny Blaze", B: "Danny Ketch", C: "Robbie Reyes", D: "Carter Slade", E: "Alejandra Jones", dogru: "A", aciklama: "En bilinen Ghost Rider, motosikletli dublör Johnny Blaze'dir." },
    { soru: "Elektra'nın sevgilisi kimdir?", A: "Daredevil", B: "Punisher", C: "Spider-Man", D: "Iron Fist", E: "Luke Cage", dogru: "A", aciklama: "Elektra Natchios, Daredevil'in sevgilisidir." },
    { soru: "Luke Cage'in lakabı nedir?", A: "Power Man", B: "Iron Fist", C: "Bulletproof", D: "Harlem Kahramanı", E: "Hepsi", dogru: "A", aciklama: "Luke Cage, 'Power Man' olarak bilinir." },
    { soru: "Iron Fist'in gerçek adı nedir?", A: "Danny Rand", B: "Orson Randall", C: "Wu Ao-Shi", D: "Bei Ming-Tian", E: "Lin Lie", dogru: "A", aciklama: "Danny Rand, ölümsüz K'un-Lun şehrinin koruyucusudur." },
    { soru: "Jessica Jones'un mesleği nedir?", A: "Özel Dedektif", B: "Avukat", C: "Gazeteci", D: "Doktor", E: "Polis", dogru: "A", aciklama: "Jessica Jones, Hell's Kitchen'da özel dedektiftir." },
    { soru: "Kingpin'in gerçek adı nedir?", A: "Wilson Fisk", B: "Wilson Grant", C: "Fisk Wilson", D: "Grant Ward", E: "Fisk Grant", dogru: "A", aciklama: "Wilson Fisk, New York'un yeraltı dünyasının acımasız lideridir." }
];
const dcSorulari = [
    { soru: "Batman'in gerçek adı nedir?", A: "Bruce Wayne", B: "Clark Kent", C: "Barry Allen", D: "Hal Jordan", E: "Oliver Queen", dogru: "A", aciklama: "Bruce Wayne, Gotham'ın milyarder koruyucusudur." },
    { soru: "Superman hangi gezegenden gelmiştir?", A: "Kripton", B: "Mars", C: "Tamaran", D: "Oa", E: "Apokolips", dogru: "A", aciklama: "Superman, Kripton gezegeninden gelen son oğuldur." },
    { soru: "Wonder Woman'ın gerçek adı nedir?", A: "Diana Prince", B: "Hippolyta", C: "Artemis", D: "Athena", E: "Hera", dogru: "A", aciklama: "Diana, Themyscira'nın prensesidir." },
    { soru: "Flash'in gerçek adı nedir?", A: "Barry Allen", B: "Wally West", C: "Jay Garrick", D: "Bart Allen", E: "Eobard Thawne", dogru: "A", aciklama: "Barry Allen, adli tıp uzmanı ve en hızlı insandır." },
    { soru: "Aquaman'in gerçek adı nedir?", A: "Arthur Curry", B: "Orin", C: "Garth", D: "Kaldur'ahm", E: "Mera", dogru: "A", aciklama: "Arthur Curry, Atlantis'in meşru kralıdır." },
    { soru: "Joker'in gerçek adı nedir?", A: "Bilinmiyor", B: "Jack Napier", C: "Arthur Fleck", D: "Joseph Kerr", E: "Jerome Valeska", dogru: "A", aciklama: "Joker'in gerçek adı çizgi romanlarda hiç açıklanmamıştır." },
    { soru: "Harley Quinn'in gerçek adı nedir?", A: "Harleen Quinzel", B: "Pamela Isley", C: "Selina Kyle", D: "Talia al Ghul", E: "Barbara Gordon", dogru: "A", aciklama: "Dr. Harleen Quinzel, Joker'in psikiyatristiyken ona aşık olmuştur." },
    { soru: "Cyborg'un gerçek adı nedir?", A: "Victor Stone", B: "Silas Stone", C: "Ray Palmer", D: "John Henry Irons", E: "Michael Holt", dogru: "A", aciklama: "Victor Stone, bir kaza sonucu sibernetik varlığa dönüşmüştür." },
    { soru: "Green Lantern yüzüğü hangi duyguyla çalışır?", A: "İrade", B: "Korku", C: "Umut", D: "Aşk", E: "Hırs", dogru: "A", aciklama: "Yeşil Fener yüzüğü, saf irade gücüyle çalışır." },
    { soru: "Darkseid'in ana hedefi nedir?", A: "Anti-Life Denklemi", B: "Dünyayı yok etmek", C: "Superman'i öldürmek", D: "Evreni fethetmek", E: "Adalet Ligi'ni yok etmek", dogru: "A", aciklama: "Anti-Life Denklemi, tüm özgür iradeyi yok edecek kozmik bir formüldür." },
    { soru: "Shazam'ın gerçek adı nedir?", A: "Billy Batson", B: "Freddy Freeman", C: "Mary Bromfield", D: "Eugene Choi", E: "Pedro Peña", dogru: "A", aciklama: "Billy Batson, 'Shazam!' diyerek yetişkin bir süper kahramana dönüşür." },
    { soru: "Catwoman'in gerçek adı nedir?", A: "Selina Kyle", B: "Pamela Isley", C: "Harleen Quinzel", D: "Talia al Ghul", E: "Barbara Gordon", dogru: "A", aciklama: "Selina Kyle, usta bir hırsız ve Batman'in aşkıdır." },
    { soru: "Nightwing'in gerçek adı nedir?", A: "Dick Grayson", B: "Jason Todd", C: "Tim Drake", D: "Damian Wayne", E: "Stephanie Brown", dogru: "A", aciklama: "Dick Grayson, ilk Robin'dir ve daha sonra Nightwing olmuştur." },
    { soru: "Red Hood'un gerçek adı nedir?", A: "Jason Todd", B: "Dick Grayson", C: "Tim Drake", D: "Damian Wayne", E: "Stephanie Brown", dogru: "A", aciklama: "Jason Todd, Joker tarafından öldürülmüş, sonra dirilmiştir." },
    { soru: "Batgirl'in gerçek adı nedir?", A: "Barbara Gordon", B: "Stephanie Brown", C: "Cassandra Cain", D: "Betty Kane", E: "Helena Bertinelli", dogru: "A", aciklama: "Barbara Gordon, Komiser Gordon'un kızı ve Oracle'dır." },
    { soru: "Superman'in en büyük zayıflığı nedir?", A: "Hepsi", B: "Kriptonit", C: "Kırmızı Güneş", D: "Büyü", E: "Su", dogru: "A", aciklama: "Superman; Kriptonit, kırmızı güneş ışığı ve büyüye karşı zayıftır." },
    { soru: "Superman'in kuzeni kimdir?", A: "Supergirl", B: "Power Girl", C: "Mary Marvel", D: "Wonder Girl", E: "Batgirl", dogru: "A", aciklama: "Kara Zor-El, Superman'in kuzeni Supergirl'dür." },
    { soru: "Superman hangi gazetede çalışır?", A: "Daily Planet", B: "Gotham Gazette", C: "Central City Citizen", D: "Star City Sentinel", E: "Metropolis News", dogru: "A", aciklama: "Clark Kent, Daily Planet'te muhabirdir." },
    { soru: "Lex Luthor ne iş yapar?", A: "Hepsi", B: "Bilim adamı", C: "İş adamı", D: "Politikacı", E: "Asker", dogru: "A", aciklama: "Lex Luthor; bilim adamı, iş adamı ve politikacıdır." },
    { soru: "Superman'in evlat edinen ailesinin soyadı nedir?", A: "Kent", B: "Wayne", C: "Parker", D: "Allen", E: "Queen", dogru: "A", aciklama: "Superman'i Jonathan ve Martha Kent evlat edinmiştir." },
    { soru: "Superman'in sevgilisinin adı nedir?", A: "Lois Lane", B: "Lana Lang", C: "Diana Prince", D: "Selina Kyle", E: "Carol Ferris", dogru: "A", aciklama: "Superman'in sevgilisi Lois Lane'dir." },
    { soru: "Superman'in köpeğinin adı nedir?", A: "Krypto", B: "Ace", C: "Rex", D: "Buddy", E: "Max", dogru: "A", aciklama: "Superman'in köpeği Krypto'dur." },
    { soru: "Superman hangi renk güneşten güç alır?", A: "Sarı", B: "Kırmızı", C: "Mavi", D: "Beyaz", E: "Yeşil", dogru: "A", aciklama: "Superman, sarı güneş ışığından güç alır." },
    { soru: "Batman'in şehri neresidir?", A: "Gotham", B: "Metropolis", C: "Central City", D: "Star City", E: "Coast City", dogru: "A", aciklama: "Batman, Gotham City'nin koruyucusudur." },
    { soru: "Batman'in sadık uşağı kimdir?", A: "Alfred Pennyworth", B: "Lucius Fox", C: "Jim Gordon", D: "Robin", E: "Harvey Bullock", dogru: "A", aciklama: "Alfred Pennyworth, Bruce Wayne'in sadık uşağıdır." },
    { soru: "Batman'in ailesini kim öldürmüştür?", A: "Joe Chill", B: "Joker", C: "Penguin", D: "Riddler", E: "Two-Face", dogru: "A", aciklama: "Joe Chill, Bruce Wayne'in ailesini öldürmüştür." },
    { soru: "Batman hangi yılda yaratılmıştır?", A: "1939", B: "1938", C: "1940", D: "1941", E: "1942", dogru: "A", aciklama: "Batman, 1939'da Detective Comics #27'de yaratılmıştır." },
    { soru: "Batcave nerededir?", A: "Wayne Malikanesi'nin altında", B: "Wayne Kulesi", C: "Gotham Polis Merkezi", D: "Arkham Asylum", E: "Gotham Limanı", dogru: "A", aciklama: "Batcave, Wayne Malikanesi'nin altındadır." },
    { soru: "Batman'in aracının adı nedir?", A: "Batmobile", B: "Batwing", C: "Batboat", D: "Batcycle", E: "Batpod", dogru: "A", aciklama: "Batman'in ikonik aracı Batmobile'dir." },
    { soru: "Robin'in gerçek adı nedir? (İlk)", A: "Dick Grayson", B: "Jason Todd", C: "Tim Drake", D: "Damian Wayne", E: "Stephanie Brown", dogru: "A", aciklama: "Dick Grayson, ilk Robin'dir." },
    { soru: "Batwoman'in gerçek adı nedir?", A: "Kate Kane", B: "Barbara Gordon", C: "Selina Kyle", D: "Helena Bertinelli", E: "Stephanie Brown", dogru: "A", aciklama: "Kate Kane, Batwoman'dır." },
    { soru: "Batman'in en büyük düşmanı kimdir?", A: "Joker", B: "Riddler", C: "Penguin", D: "Two-Face", E: "Bane", dogru: "A", aciklama: "Joker, Batman'in en büyük düşmanıdır." },
    { soru: "Flash'in düşmanı Reverse-Flash'in gerçek adı nedir?", A: "Eobard Thawne", B: "Hunter Zolomon", C: "Daniel West", D: "Edward Clariss", E: "August Heart", dogru: "A", aciklama: "Eobard Thawne, 25. yüzyıldan gelen Reverse-Flash'tir." },
    { soru: "Green Arrow'un gerçek adı nedir?", A: "Oliver Queen", B: "Clint Barton", C: "Roy Harper", D: "John Diggle", E: "Malcolm Merlyn", dogru: "A", aciklama: "Oliver Queen, Star City'nin koruyucusu Green Arrow'dur." },
    { soru: "Black Canary'nin gerçek adı nedir?", A: "Dinah Lance", B: "Laurel Lance", C: "Sara Lance", D: "Dinah Drake", E: "Helena Bertinelli", dogru: "A", aciklama: "Dinah Lance, Black Canary'dir." },
    { soru: "Martian Manhunter'ın gerçek adı nedir?", A: "J'onn J'onzz", B: "M'gann M'orzz", C: "Kal-El", D: "Bruce Wayne", E: "Barry Allen", dogru: "A", aciklama: "J'onn J'onzz, Mars'tan gelen son yeşil marslıdır." },
    { soru: "Hawkman'in gerçek adı nedir?", A: "Carter Hall", B: "Katar Hol", C: "Felix Faust", D: "Vandal Savage", E: "Shayera Hol", dogru: "A", aciklama: "Carter Hall, Hawkman'in reenkarne olmuş halidir." },
    { soru: "Hawkgirl'ün gerçek adı nedir?", A: "Shayera Hol", B: "Kendra Saunders", C: "Dinah Lance", D: "Zatanna", E: "Mera", dogru: "A", aciklama: "Shayera Hol, Hawkgirl'ün Thanagarian versiyonudur." },
    { soru: "Zatanna'nın gücü nedir?", A: "Büyü", B: "Süper Hız", C: "Süper Güç", D: "Uçma", E: "Görünmezlik", dogru: "A", aciklama: "Zatanna, güçlü bir büyücüdür." },
    { soru: "John Constantine'in lakabı nedir?", A: "Hellblazer", B: "Exorcist", C: "Warlock", D: "Sorcerer", E: "Magician", dogru: "A", aciklama: "John Constantine, Hellblazer olarak bilinir." }
];
const oyunSorulari = [
    { soru: "CS:GO'da en popüler harita hangisidir?", A: "Dust II", B: "Mirage", C: "Inferno", D: "Nuke", E: "Vertigo", dogru: "A", aciklama: "Dust II, Counter-Strike'ın ikonik haritasıdır." },
    { soru: "LoL'de 'Pentakill' ne demektir?", A: "Tek başına 5 rakip öldürmek", B: "5 asist", C: "5 ölüm", D: "5 kule yıkmak", E: "5 ejderha kesmek", dogru: "A", aciklama: "Pentakill, kısa sürede tek başına 5 düşman şampiyonu öldürmektir." },
    { soru: "Minecraft hangi yılda piyasaya sürülmüştür?", A: "2011", B: "2009", C: "2013", D: "2015", E: "2017", dogru: "A", aciklama: "Minecraft tam sürüm olarak 2011'de yayınlanmıştır." },
    { soru: "Valorant'ta Vandal'ın headshot hasarı kaçtır?", A: "160", B: "150", C: "156", D: "165", E: "170", dogru: "A", aciklama: "Vandal, 0-50m arası headshotta 160 hasar verir." },
    { soru: "Fortnite hangi yıl Battle Royale modunu eklemiştir?", A: "2017", B: "2016", C: "2018", D: "2019", E: "2020", dogru: "A", aciklama: "Fortnite Battle Royale, 2017'de ücretsiz olarak yayınlanmıştır." },
    { soru: "GTA V hangi yıl piyasaya sürülmüştür?", A: "2013", B: "2011", C: "2015", D: "2017", E: "2019", dogru: "A", aciklama: "Grand Theft Auto V, 2013'te piyasaya sürülmüştür." },
    { soru: "PUBG'nin açılımı nedir?", A: "PlayerUnknown's Battlegrounds", B: "Public Unknown Battle Grounds", C: "Player Ultimate Battle Grounds", D: "Public Universal Battle Game", E: "Player's Unknown Battle Game", dogru: "A", aciklama: "PUBG, Brendan Greene tarafından yaratılmıştır." },
    { soru: "Call of Duty: Warzone kaç oyunculudur?", A: "150", B: "100", C: "120", D: "200", E: "50", dogru: "A", aciklama: "Warzone, 150 oyunculu battle royale moduna sahiptir." },
    { soru: "The Legend of Zelda: Breath of the Wild hangi konsola özeldir?", A: "Nintendo Switch", B: "PlayStation 4", C: "Xbox One", D: "PC", E: "Wii U", dogru: "A", aciklama: "Oyun hem Switch hem Wii U için çıkmıştır, ancak Switch ile özdeşleşmiştir." },
    { soru: "Among Us kaç oyuncuyla oynanabilir? (Maksimum)", A: "15", B: "10", C: "12", D: "8", E: "20", dogru: "A", aciklama: "Among Us, 4-15 oyuncu ile oynanabilir." },
    { soru: "Elden Ring'in yönetmeni kimdir?", A: "Hidetaka Miyazaki", B: "Hideo Kojima", C: "Shigeru Miyamoto", D: "Shinji Mikami", E: "Yoko Taro", dogru: "A", aciklama: "Miyazaki, Dark Souls serisinin de yaratıcısıdır." },
    { soru: "God of War (2018) hangi mitolojiyi konu alır?", A: "İskandinav", B: "Yunan", C: "Mısır", D: "Japon", E: "Kelt", dogru: "A", aciklama: "Yeni God of War, İskandinav mitolojisinde geçer." },
    { soru: "The Witcher 3'ün ana karakteri kimdir?", A: "Geralt of Rivia", B: "Ciri", C: "Yennefer", D: "Triss", E: "Vesemir", dogru: "A", aciklama: "Geralt, Rivyalı bir witcher'dır." },
    { soru: "Red Dead Redemption 2 hangi yıl çıkmıştır?", A: "2018", B: "2016", C: "2017", D: "2019", E: "2020", dogru: "A", aciklama: "RDR2, Rockstar Games tarafından 2018'de piyasaya sürülmüştür." },
    { soru: "Hangisi bir battle royale oyunu değildir?", A: "CS:GO", B: "Fortnite", C: "PUBG", D: "Apex Legends", E: "Warzone", dogru: "A", aciklama: "CS:GO taktiksel FPS'dir, battle royale modu yoktur." },
    { soru: "Super Mario'nun yaratıcısı kimdir?", A: "Shigeru Miyamoto", B: "Hideo Kojima", C: "Satoru Iwata", D: "Shinji Mikami", E: "Gabe Newell", dogru: "A", aciklama: "Shigeru Miyamoto, Mario'nun yaratıcısıdır." },
    { soru: "PlayStation hangi şirketin ürünüdür?", A: "Sony", B: "Microsoft", C: "Nintendo", D: "Sega", E: "Atari", dogru: "A", aciklama: "PlayStation, Sony Interactive Entertainment'ın oyun konsoludur." },
    { soru: "Dünyanın en çok satan oyunu hangisidir?", A: "Minecraft", B: "Tetris", C: "GTA V", D: "Wii Sports", E: "PUBG", dogru: "A", aciklama: "Minecraft 300 milyondan fazla satmıştır." },
    { soru: "Hangisi bir oyun motoru değildir?", A: "Photoshop", B: "Unity", C: "Unreal Engine", D: "Godot", E: "CryEngine", dogru: "A", aciklama: "Photoshop grafik tasarım programıdır." },
    { soru: "Valorant hangi şirketin oyunudur?", A: "Riot Games", B: "Valve", C: "Blizzard", D: "Epic Games", E: "EA", dogru: "A", aciklama: "Valorant, Riot Games'in FPS oyunudur." },
    { soru: "The Legend of Zelda serisinin ana karakteri kimdir?", A: "Link", B: "Zelda", C: "Ganon", D: "Mario", E: "Kirby", dogru: "A", aciklama: "Ana karakter Link'tir, Zelda prensestir." },
    { soru: "Hangisi bir espor oyunu değildir?", A: "The Sims", B: "League of Legends", C: "Dota 2", D: "CS2", E: "Valorant", dogru: "A", aciklama: "The Sims yaşam simülasyonu oyunudur, espor değildir." },
    { soru: "Pokemon'daki Pikachu hangi türdür?", A: "Elektrik", B: "Ateş", C: "Su", D: "Çim", E: "Normal", dogru: "A", aciklama: "Pikachu elektrik türü bir pokemondur." },
    { soru: "Hangisi bir Resident Evil oyunu değildir?", A: "Silent Hill", B: "RE2", C: "RE4", D: "RE7", E: "Village", dogru: "A", aciklama: "Silent Hill, Konami'nin korku oyunu serisidir." },
    { soru: "Hangisi bir Assassin's Creed oyunu değildir?", A: "Far Cry", B: "Black Flag", C: "Valhalla", D: "Odyssey", E: "Mirage", dogru: "A", aciklama: "Far Cry, Ubisoft'un ayrı bir serisidir." },
    { soru: "Hangisi bir Need for Speed oyunu değildir?", A: "Forza Horizon", B: "Most Wanted", C: "Underground", D: "Carbon", E: "Heat", dogru: "A", aciklama: "Forza Horizon, Xbox'a özel yarış serisidir." },
    { soru: "Hangisi bir FIFA (EA FC) oyunu değildir?", A: "PES", B: "FIFA 23", C: "EA FC 24", D: "FIFA 22", E: "EA FC 25", dogru: "A", aciklama: "PES (eFootball), Konami'nin futbol oyunudur." },
    { soru: "Hangisi bir Call of Duty oyunu değildir?", A: "Battlefield", B: "Modern Warfare", C: "Black Ops", D: "Warzone", E: "Vanguard", dogru: "A", aciklama: "Battlefield, EA'in FPS serisidir." },
    { soru: "Hangisi bir GTA oyunu değildir?", A: "Watch Dogs", B: "Vice City", C: "San Andreas", D: "GTA IV", E: "GTA V", dogru: "A", aciklama: "Watch Dogs, Ubisoft'un aksiyon-macera oyunudur." },
    { soru: "Hangisi bir Soulsborne oyunu değildir?", A: "Sekiro", B: "Dark Souls", C: "Bloodborne", D: "Elden Ring", E: "Demon's Souls", dogru: "A", aciklama: "Sekiro, FromSoftware'in oyunu olsa da Soulsborne sayılmaz (mekanik farkı)." },
    { soru: "Hangisi bir Bethesda oyunu değildir?", A: "Cyberpunk 2077", B: "Skyrim", C: "Fallout 4", D: "Starfield", E: "Oblivion", dogru: "A", aciklama: "Cyberpunk 2077, CD Projekt Red'in oyunudur." },
    { soru: "Hangisi bir Blizzard oyunu değildir?", A: "League of Legends", B: "World of Warcraft", C: "Diablo", D: "Overwatch", E: "Starcraft", dogru: "A", aciklama: "League of Legends, Riot Games'in oyunudur." },
    { soru: "Hangisi bir Valve oyunu değildir?", A: "Overwatch", B: "Half-Life", C: "Portal", D: "Dota 2", E: "CS2", dogru: "A", aciklama: "Overwatch, Blizzard'ın oyunudur." },
    { soru: "Hangisi bir Epic Games oyunu değildir?", A: "PUBG", B: "Fortnite", C: "Gears of War", D: "Unreal Tournament", E: "Infinity Blade", dogru: "A", aciklama: "PUBG, Krafton'un oyunudur." },
    { soru: "Hangisi bir Rockstar Games oyunu değildir?", A: "Mafia", B: "GTA", C: "Red Dead", D: "Max Payne", E: "Bully", dogru: "A", aciklama: "Mafia, 2K Games'in serisidir." },
    { soru: "Hangisi bir korku oyunu değildir?", A: "Stardew Valley", B: "Resident Evil", C: "Silent Hill", D: "Amnesia", E: "Outlast", dogru: "A", aciklama: "Stardew Valley, çiftlik simülasyonudur." },
    { soru: "Hangisi bir RPG oyunu değildir?", A: "FIFA", B: "Skyrim", C: "The Witcher 3", D: "Final Fantasy", E: "Baldur's Gate 3", dogru: "A", aciklama: "FIFA, spor oyunudur." },
    { soru: "Hangisi bir strateji oyunu değildir?", A: "Minecraft", B: "Age of Empires", C: "Civilization", D: "Starcraft", E: "Total War", dogru: "A", aciklama: "Minecraft, sandbox hayatta kalma oyunudur." },
    { soru: "Hangisi bir simülasyon oyunu değildir?", A: "Doom", B: "Flight Simulator", C: "The Sims", D: "Euro Truck Simulator", E: "Farming Simulator", dogru: "A", aciklama: "Doom, FPS oyunudur." },
    { soru: "Hangisi bir bağımsız (indie) oyun değildir?", A: "Call of Duty", B: "Hades", C: "Stardew Valley", D: "Celeste", E: "Hollow Knight", dogru: "A", aciklama: "Call of Duty, büyük bir stüdyonun AAA oyunudur." }
];
const arabaSorulari = [
    { soru: "Ferrari'nin logosundaki hayvan nedir?", A: "At", B: "Boğa", C: "Aslan", D: "Kartal", E: "Panter", dogru: "A", aciklama: "Şaha kalkmış siyah at, Ferrari'nin simgesidir." },
    { soru: "Lamborghini'nin logosundaki hayvan nedir?", A: "Boğa", B: "At", C: "Aslan", D: "Kartal", E: "Yılan", dogru: "A", aciklama: "Altın boğa, Lamborghini'nin gücünü temsil eder." },
    { soru: "Porsche 911'in motoru nerede bulunur?", A: "Arkada", B: "Önde", C: "Ortada", D: "Her yerde", E: "Hiçbiri", dogru: "A", aciklama: "Porsche 911, arkadan motorlu klasik bir spor arabadır." },
    { soru: "Bugatti Veyron'un maksimum hızı kaç km/s'tir?", A: "407", B: "350", C: "380", D: "420", E: "450", dogru: "A", aciklama: "Bugatti Veyron Super Sport 407 km/s hıza ulaşabilir." },
    { soru: "Tesla'nın CEO'su kimdir?", A: "Elon Musk", B: "Jeff Bezos", C: "Bill Gates", D: "Mark Zuckerberg", E: "Tim Cook", dogru: "A", aciklama: "Elon Musk, Tesla ve SpaceX'in CEO'sudur." },
    { soru: "Mercedes-Benz hangi ülkenin markasıdır?", A: "Almanya", B: "Fransa", C: "İtalya", D: "İngiltere", E: "ABD", dogru: "A", aciklama: "Mercedes, Alman otomotiv devidir." },
    { soru: "BMW'nin açılımı nedir?", A: "Bayerische Motoren Werke", B: "Bavarian Motor Works", C: "Berlin Motor Works", D: "British Motor Works", E: "Belgian Motor Works", dogru: "A", aciklama: "BMW, Bavyera Motor Fabrikaları anlamına gelir." },
    { soru: "Audi'nin sloganı nedir?", A: "Vorsprung durch Technik", B: "Das Auto", C: "The Ultimate Driving Machine", D: "Sheer Driving Pleasure", E: "Power of Dreams", dogru: "A", aciklama: "Vorsprung durch Technik, 'Teknolojiyle Önde' demektir." },
    { soru: "Hangi araba James Bond ile özdeşleşmiştir?", A: "Aston Martin", B: "Jaguar", C: "Bentley", D: "Rolls-Royce", E: "Lotus", dogru: "A", aciklama: "Aston Martin DB5, James Bond'un ikonik aracıdır." },
    { soru: "Hangisi bir Amerikan otomobil markasıdır?", A: "Chevrolet", B: "Renault", C: "Peugeot", D: "Fiat", E: "Seat", dogru: "A", aciklama: "Chevrolet, General Motors'a ait Amerikan markasıdır." },
    { soru: "Hangisi bir Japon otomobil markasıdır?", A: "Toyota", B: "Hyundai", C: "Kia", D: "Volvo", E: "Saab", dogru: "A", aciklama: "Toyota, Japon otomotiv devidir." },
    { soru: "Formula 1'de en çok şampiyonluk kazanan takım hangisidir?", A: "Ferrari", B: "Mercedes", C: "Red Bull", D: "McLaren", E: "Williams", dogru: "A", aciklama: "Ferrari, 16 markalar şampiyonluğu kazanmıştır." },
    { soru: "Hangi araba 'kanat kapılar' ile ünlüdür?", A: "Lamborghini", B: "Ferrari", C: "Porsche", D: "Bugatti", E: "McLaren", dogru: "A", aciklama: "Lamborghini'nin makas kapıları ikoniktir." },
    { soru: "Elektrikli otomobil üreticisi Rivian hangi ülkedendir?", A: "ABD", B: "Çin", C: "Almanya", D: "Japonya", E: "İngiltere", dogru: "A", aciklama: "Rivian, Amerikan elektrikli araç girişimidir." },
    { soru: "Hangisi bir Fransız otomobil markasıdır?", A: "Renault", B: "Fiat", C: "Seat", D: "Opel", E: "Skoda", dogru: "A", aciklama: "Renault, Fransız otomobil üreticisidir." },
    { soru: "Hangisi bir İtalyan otomobil markası değildir?", A: "Volkswagen", B: "Ferrari", C: "Lamborghini", D: "Maserati", E: "Alfa Romeo", dogru: "A", aciklama: "Volkswagen, Alman markasıdır." },
    { soru: "Hangisi bir Alman otomobil markası değildir?", A: "Volvo", B: "BMW", C: "Mercedes", D: "Audi", E: "Porsche", dogru: "A", aciklama: "Volvo, İsveç markasıdır." },
    { soru: "Hangisi bir İngiliz otomobil markasıdır?", A: "Jaguar", B: "Ferrari", C: "Porsche", D: "Tesla", E: "Toyota", dogru: "A", aciklama: "Jaguar, İngiliz lüks otomobil üreticisidir." },
    { soru: "Hangisi bir süper spor otomobil değildir?", A: "Fiat Egea", B: "Bugatti Chiron", C: "Koenigsegg Jesko", D: "Pagani Huayra", E: "Rimac Nevera", dogru: "A", aciklama: "Fiat Egea, ekonomik bir aile otomobilidir." },
    { soru: "Hangisi bir SUV modelidir?", A: "Toyota RAV4", B: "Toyota Corolla", C: "Honda Civic", D: "BMW 3 Serisi", E: "Mercedes E Serisi", dogru: "A", aciklama: "RAV4, Toyota'nın kompakt SUV modelidir." },
    { soru: "Hangisi bir pick-up modelidir?", A: "Ford F-150", B: "Ford Focus", C: "Honda Civic", D: "Toyota Corolla", E: "VW Golf", dogru: "A", aciklama: "Ford F-150, Amerika'nın en çok satan pick-up'ıdır." },
    { soru: "Hangisi bir elektrikli otomobil modeli değildir?", A: "Toyota Hilux", B: "Tesla Model 3", C: "Rivian R1T", D: "Lucid Air", E: "Porsche Taycan", dogru: "A", aciklama: "Toyota Hilux, dizel pick-up'tır." },
    { soru: "Hangisi bir hibrit otomobil modelidir?", A: "Toyota Prius", B: "Tesla Model S", C: "Nissan Leaf", D: "BMW i3", E: "Ford Mustang Mach-E", dogru: "A", aciklama: "Prius, dünyanın en popüler hibrit otomobilidir." },
    { soru: "Hangisi bir lüks otomobil markası değildir?", A: "Dacia", B: "Rolls-Royce", C: "Bentley", D: "Maybach", E: "Aston Martin", dogru: "A", aciklama: "Dacia, ekonomik otomobiller üreten Romanya markasıdır." },
    { soru: "Hangisi bir otomobil yarışı serisi değildir?", A: "UEFA Şampiyonlar Ligi", B: "Formula 1", C: "WRC", D: "NASCAR", E: "Le Mans", dogru: "A", aciklama: "UEFA Şampiyonlar Ligi, futbol turnuvasıdır." },
    { soru: "Hangisi bir Formula 1 pilotu değildir?", A: "Valentino Rossi", B: "Lewis Hamilton", C: "Max Verstappen", D: "Charles Leclerc", E: "Fernando Alonso", dogru: "A", aciklama: "Valentino Rossi, MotoGP pilotudur." },
    { soru: "Hangisi bir ralli pilotu değildir?", A: "Michael Schumacher", B: "Sébastien Loeb", C: "Sébastien Ogier", D: "Carlos Sainz", E: "Kalle Rovanperä", dogru: "A", aciklama: "Michael Schumacher, Formula 1 pilotudur." },
    { soru: "Otomobillerde ABS ne işe yarar?", A: "Frenlemede direksiyon hakimiyetini korumak", B: "Daha hızlı durmak", C: "Yakıt tasarrufu", D: "Daha yumuşak fren", E: "Motor gücünü artırmak", dogru: "A", aciklama: "ABS, tekerleklerin kilitlenmesini önleyerek direksiyon kontrolünü sağlar." },
    { soru: "Otomobillerde ESP ne işe yarar?", A: "Aracın savrulmasını önlemek", B: "Hız sabitleyici", C: "Yokuş kalkış desteği", D: "Şerit takip asistanı", E: "Otomatik park", dogru: "A", aciklama: "ESP (Elektronik Stabilite Programı), aracın kaymasını ve savrulmasını engeller." },
    { soru: "Hangisi bir otomobil yakıt türü değildir?", A: "Hidroelektrik", B: "Benzin", C: "Dizel", D: "LPG", E: "Elektrik", dogru: "A", aciklama: "Hidroelektrik, elektrik üretim yöntemidir." },
    { soru: "Hangisi bir otomobil şanzıman türü değildir?", A: "Hidrolik", B: "Manuel", C: "Otomatik", D: "Yarı Otomatik", E: "CVT", dogru: "A", aciklama: "Hidrolik, güç aktarım sistemi değildir." },
    { soru: "Hangisi bir otomobil segmenti değildir?", A: "Hatchback", B: "Sedan", C: "SUV", D: "Coupe", E: "Apartman", dogru: "E", aciklama: "Apartman, otomobil segmenti değildir." },
    { soru: "Hangisi bir Türk otomobil markasıdır?", A: "TOGG", B: "BMC", C: "Otokar", D: "Karsan", E: "Hepsi", dogru: "A", aciklama: "TOGG, Türkiye'nin yerli elektrikli otomobil markasıdır." },
    { soru: "Hangisi bir İtalyan spor otomobil markasıdır?", A: "Pagani", B: "Koenigsegg", C: "Spyker", D: "Noble", E: "Wiesmann", dogru: "A", aciklama: "Pagani, İtalyan süper spor otomobil üreticisidir." },
    { soru: "Hangisi bir İsveç otomobil markasıdır?", A: "Volvo", B: "Saab", C: "Koenigsegg", D: "Hepsi", E: "Scania", dogru: "D", aciklama: "Volvo, Saab, Koenigsegg ve Scania İsveç markalarıdır." },
    { soru: "Hangisi bir Güney Kore otomobil markası değildir?", A: "Mazda", B: "Hyundai", C: "Kia", D: "Genesis", E: "SsangYong", dogru: "A", aciklama: "Mazda, Japon markasıdır." },
    { soru: "Hangisi bir Çin otomobil markasıdır?", A: "BYD", B: "Toyota", C: "Honda", D: "Nissan", E: "Mitsubishi", dogru: "A", aciklama: "BYD, Çinli elektrikli otomobil üreticisidir." },
    { soru: "Hangisi bir motosiklet markası değildir?", A: "Subaru", B: "Honda", C: "Yamaha", D: "Kawasaki", E: "Suzuki", dogru: "A", aciklama: "Subaru, otomobil markasıdır." },
    { soru: "Hangisi bir lastik markası değildir?", A: "Brembo", B: "Michelin", C: "Pirelli", D: "Goodyear", E: "Bridgestone", dogru: "A", aciklama: "Brembo, fren sistemi üreticisidir." },
    { soru: "Hangisi bir otomobil parçası değildir?", A: "Pervane", B: "Motor", C: "Şanzıman", D: "Direksiyon", E: "Egzoz", dogru: "A", aciklama: "Pervane, uçak veya gemilerde bulunur." }
];
const motorSorulari = [
    { soru: "Hayabusa hangi markanın modelidir?", A: "Suzuki", B: "Yamaha", C: "Kawasaki", D: "Honda", E: "Ducati", dogru: "A", aciklama: "Suzuki Hayabusa, dünyanın en hızlı seri üretim motosikletlerindendir." },
    { soru: "Yamaha R1'in motor hacmi kaç cc'dir?", A: "998", B: "1000", C: "750", D: "1100", E: "1200", dogru: "A", aciklama: "Yamaha YZF-R1, 998cc sıvı soğutmalı motora sahiptir." },
    { soru: "BMW motosikletlerinin sloganı nedir?", A: "Make Life a Ride", B: "The Ultimate Riding Machine", C: "Unstoppable", D: "Born to Ride", E: "Ride and Enjoy", dogru: "A", aciklama: "BMW Motorrad'ın sloganı 'Make Life a Ride'dır." },
    { soru: "Ducati hangi ülkenin markasıdır?", A: "İtalya", B: "Almanya", C: "Japonya", D: "ABD", E: "İngiltere", dogru: "A", aciklama: "Ducati, İtalyan lüks motosiklet üreticisidir." },
    { soru: "Kawasaki Ninja H2R'nin maksimum gücü kaç beygirdir?", A: "310", B: "200", C: "250", D: "280", E: "350", dogru: "A", aciklama: "H2R, süperşarjlı motoruyla 310+ beygir güç üretir." },
    { soru: "Honda CBR serisi hangi tür motosikletlerdir?", A: "Spor", B: "Cruiser", C: "Touring", D: "Adventure", E: "Naked", dogru: "A", aciklama: "CBR, Honda'nın spor motosiklet ailesidir." },
    { soru: "Harley-Davidson hangi tür motosikletleriyle ünlüdür?", A: "Cruiser", B: "Spor", C: "Touring", D: "Adventure", E: "Scooter", dogru: "A", aciklama: "Harley-Davidson, V-twin cruiser motosikletleriyle tanınır." },
    { soru: "MotoGP'de en çok şampiyonluk kazanan sürücü kimdir?", A: "Giacomo Agostini", B: "Valentino Rossi", C: "Marc Marquez", D: "Mick Doohan", E: "Jorge Lorenzo", dogru: "A", aciklama: "Giacomo Agostini, 15 dünya şampiyonluğu kazanmıştır." },
    { soru: "Hangisi bir İtalyan motosiklet markasıdır?", A: "Aprilia", B: "Triumph", C: "KTM", D: "Royal Enfield", E: "Moto Guzzi", dogru: "A", aciklama: "Aprilia, İtalyan motosiklet üreticisidir." },
    { soru: "Hangisi bir motosiklet güvenlik ekipmanı değildir?", A: "Kravat", B: "Kask", C: "Eldiven", D: "Ceket", E: "Dizlik", dogru: "A", aciklama: "Kravat motosiklet güvenlik ekipmanı değildir." },
    { soru: "Hangisi bir İngiliz motosiklet markasıdır?", A: "Triumph", B: "Ducati", C: "BMW", D: "KTM", E: "Husqvarna", dogru: "A", aciklama: "Triumph, İngiliz motosiklet üreticisidir." },
    { soru: "Hangisi bir Avusturya motosiklet markasıdır?", A: "KTM", B: "BMW", C: "Ducati", D: "Aprilia", E: "Yamaha", dogru: "A", aciklama: "KTM, Avusturyalı motosiklet üreticisidir." },
    { soru: "Hangisi bir Alman motosiklet markasıdır?", A: "BMW", B: "Ducati", C: "Aprilia", D: "KTM", E: "Honda", dogru: "A", aciklama: "BMW Motorrad, Alman motosiklet üreticisidir." },
    { soru: "Hangisi bir Japon motosiklet markası değildir?", A: "Ducati", B: "Honda", C: "Yamaha", D: "Suzuki", E: "Kawasaki", dogru: "A", aciklama: "Ducati, İtalyan markasıdır." },
    { soru: "Hangisi bir motosiklet türü değildir?", A: "Cabrio", B: "Spor", C: "Cruiser", D: "Touring", E: "Naked", dogru: "A", aciklama: "Cabrio, otomobil türüdür." },
    { soru: "Hangisi bir scooter markası değildir?", A: "Harley-Davidson", B: "Vespa", C: "Peugeot", D: "Aprilia", E: "Honda", dogru: "A", aciklama: "Harley-Davidson, büyük hacimli cruiser'larla bilinir." },
    { soru: "Hangisi bir elektrikli motosiklet markasıdır?", A: "Zero Motorcycles", B: "Harley-Davidson", C: "Indian", D: "Triumph", E: "Moto Guzzi", dogru: "A", aciklama: "Zero Motorcycles, elektrikli motosiklet üretir." },
    { soru: "Harley-Davidson'ın elektrikli motosiklet markası nedir?", A: "LiveWire", B: "Zero", C: "Energica", D: "Lightning", E: "Damon", dogru: "A", aciklama: "LiveWire, Harley-Davidson'ın elektrikli motosiklet markasıdır." },
    { soru: "Motosikletlerde ABS ne işe yarar?", A: "Frenlemede tekerlek kilitlenmesini önlemek", B: "Daha hızlı hızlanmak", C: "Yakıt tasarrufu", D: "Daha yüksek hız", E: "Motor gücünü artırmak", dogru: "A", aciklama: "ABS, ani frenlemede tekerleklerin kilitlenmesini engeller." },
    { soru: "Hangisi bir motosiklet ehliyet sınıfı değildir?", A: "B Sınıfı", B: "A1", C: "A2", D: "A", E: "M", dogru: "A", aciklama: "B Sınıfı otomobil ehliyetidir." },
    { soru: "Hangisi bir motosiklet yarışı serisi değildir?", A: "Formula 1", B: "MotoGP", C: "Superbike", D: "Moto2", E: "Moto3", dogru: "A", aciklama: "Formula 1, otomobil yarışıdır." },
    { soru: "Valentino Rossi'nin lakabı nedir?", A: "The Doctor", B: "The Professor", C: "The GOAT", D: "The King", E: "The Magician", dogru: "A", aciklama: "Valentino Rossi, 'The Doctor' lakabıyla bilinir." },
    { soru: "Hangisi bir Türk motosiklet markasıdır?", A: "Kuba", B: "Honda", C: "Yamaha", D: "Suzuki", E: "Kawasaki", dogru: "A", aciklama: "Kuba, Türkiye'de motosiklet üreten bir markadır." },
    { soru: "Hangisi bir Mondial motosiklet modeli değildir?", A: "CBR", B: "Drift", C: "Snake", D: "RX", E: "Z-one", dogru: "A", aciklama: "CBR, Honda'nın spor motosiklet serisidir." },
    { soru: "Hangisi bir Kanuni motosiklet modelidir?", A: "Tiger", B: "Falcon", C: "Eagle", D: "Lion", E: "Panther", dogru: "A", aciklama: "Kanuni Tiger, popüler bir yerli motosiklet modelidir." },
    { soru: "Hangisi bir çift silindirli motosiklet türüdür?", A: "V-Twin", B: "Inline-4", C: "V4", D: "Single", E: "Boxer", dogru: "A", aciklama: "V-Twin, iki silindirin V şeklinde dizildiği motor tipidir." },
    { soru: "Hangisi bir dört silindirli motosiklet türüdür?", A: "Inline-4", B: "V-Twin", C: "Single", D: "Boxer Twin", E: "V4", dogru: "A", aciklama: "Inline-4, dört silindirin sıralı olduğu motordur." },
    { soru: "Hangisi bir motosiklet markası değildir?", A: "Ray-Ban", B: "Honda", C: "Yamaha", D: "Suzuki", E: "Kawasaki", dogru: "A", aciklama: "Ray-Ban, gözlük markasıdır." },
    { soru: "Hangisi bir motosiklet aksesuarı değildir?", A: "Spoiler", B: "Kask", C: "Eldiven", D: "Mont", E: "Çanta", dogru: "A", aciklama: "Spoiler, otomobiller için aerodinamik parçadır." },
    { soru: "Hangisi bir motosiklet fren sistemi değildir?", A: "ABS", B: "Disk Fren", C: "Kampana Fren", D: "CBS", E: "Hepsi fren sistemidir", dogru: "A", aciklama: "ABS bir fren sistemi değil, fren destek sistemidir." },
    { soru: "Hangisi bir arazi (off-road) motosikleti türü değildir?", A: "Supersport", B: "Enduro", C: "Cross", D: "Trial", E: "Adventure", dogru: "A", aciklama: "Supersport, pist ve yol odaklı spor motosikletlerdir." },
    { soru: "Hangisi bir motosiklet süspansiyon markası değildir?", A: "Brembo", B: "Öhlins", C: "Showa", D: "KYB", E: "WP", dogru: "A", aciklama: "Brembo, fren markasıdır." },
    { soru: "Hangisi bir motosiklet lastik markası değildir?", A: "Bosch", B: "Pirelli", C: "Michelin", D: "Metzeler", E: "Bridgestone", dogru: "A", aciklama: "Bosch, otomotiv elektroniği üreticisidir." },
    { soru: "Hangisi bir motosiklet egzoz markası değildir?", A: "K&N", B: "Akrapovič", C: "Yoshimura", D: "Termignoni", E: "SC Project", dogru: "A", aciklama: "K&N, hava filtresi üreticisidir." },
    { soru: "Hangisi bir motosiklet koruma ekipmanı markasıdır?", A: "Dainese", B: "Arai", C: "Shoei", D: "Alpinestars", E: "Hepsi", dogru: "E", aciklama: "Dainese, Arai, Shoei, Alpinestars koruma ekipmanı markalarıdır." },
    { soru: "Hangisi bir motosiklet kaskı markası değildir?", A: "Ray-Ban", B: "Arai", C: "Shoei", D: "AGV", E: "HJC", dogru: "A", aciklama: "Ray-Ban, gözlük markasıdır." },
    { soru: "Hangisi bir motosiklet iletişim sistemi markasıdır?", A: "Cardo", B: "Sena", C: "Interphone", D: "Midland", E: "Hepsi", dogru: "E", aciklama: "Cardo, Sena, Interphone, Midland iletişim sistemi markalarıdır." },
    { soru: "Hangisi bir motosiklet navigasyon markasıdır?", A: "Garmin", B: "TomTom", C: "Beeline", D: "Hepsi", E: "Apple", dogru: "D", aciklama: "Garmin, TomTom, Beeline motosiklet navigasyon markalarıdır." },
    { soru: "Hangisi bir motosiklet aksiyon kamerası markasıdır?", A: "GoPro", B: "DJI", C: "Insta360", D: "Hepsi", E: "SJCAM", dogru: "D", aciklama: "GoPro, DJI, Insta360, SJCAM aksiyon kamerası markalarıdır." },
    { soru: "Hangisi bir motosiklet akrobasi hareketi değildir?", A: "Drift", B: "Wheelie", C: "Stoppie", D: "Burnout", E: "Endo", dogru: "A", aciklama: "Drift, otomobillerle yapılan bir kaydırma tekniğidir." }
];